// Served via Pages middleware: the CSP exceeds Cloudflare Pages' _headers
// per-header limit, so _headers would drop it. Regenerate via scripts/update_csp_hashes.py.
const CSP = `default-src 'self'; script-src 'self' blob: https://unpkg.com https://cdn.jsdelivr.net https://*.elevenlabs.io https://*.daily.co https://static.cloudflareinsights.com https://challenges.cloudflare.com https://js.stripe.com https://www.googletagmanager.com https://www.google-analytics.com https://mc.yandex.ru https://mc.yandex.net https://mc.yandex.com 'sha256-+xm/cl7w04e6D4Jxr/blGe5FGYltVFeOqO/Y5nXELK0=' 'sha256-0wClGbGlLn7PQ446/nMrQIYNuPh5ogv0ubUo2DOdG6w=' 'sha256-2+BknAVMKCuZmvxsGEd/+ZQOFy4h7NKA2qHfD4U5fy4=' 'sha256-3Qc8Jcph364kGAGDx+ahc8BAwo9JJZQ//mcihVCTHhs=' 'sha256-63R59nlkKwyNj6v2oj6ub/VlClsUHteHq4KBt/bfFBI=' 'sha256-8KDkI21VPRWgn74R//hfvqXctgxmXrIe97HnbofWy00=' 'sha256-A1TEAvoyDjT8tRJj2jXi8Tegm9oreCsim6PzVRzAFjI=' 'sha256-D1GEQCgANKnvAtdvElL6tIFVbebNIwyhNdGoCi8zCUg=' 'sha256-E04FOytnPze7zA2XKrp791jBqsPzmHmfWwDt/j3tTSA=' 'sha256-F7G/QvBzd73kqNQZiihtrVEhd/fBU4TelkcFa1LVbac=' 'sha256-FNWn02YgQ428780FknGu3NuNkE5sAbQVcCstbpkEK+U=' 'sha256-Fv2b9fVssVYAn7iEevw0s1nDkwxmA4UJlAZldhzFliE=' 'sha256-GuCarPNKYix76zmNCJ9EVwtOkDosVvNPytMimKTLVC8=' 'sha256-H7o//z46HEAc0JNF/JsJAuWitdfyJLsJMTVIugW2YUY=' 'sha256-Hf0Z2PfGSlAPa2vId/lttm3GrQF2RudpbvZP9BFUduM=' 'sha256-OsnFlBR1Z22kaUGXI6zhFyqPXB++h9M4jfSOGdc8rHs=' 'sha256-PnnqsHGdLrw5VH9txKce80LPBNl0rQB9kNb2MYeU9KE=' 'sha256-Pu/yE7Prp1iOpmvP1ssarxvG33XttUxIzDkJac6AWKs=' 'sha256-UK6n2eu2Buqt2n5+IKddJOqFKBxq5n6FsUbIdo3amys=' 'sha256-UOhRVowBAj+2fmIftx+e3PEpB4vaG/rMyIfdcbVIbJs=' 'sha256-Ur7zuzbNNAZsC1tky+7sqtsGaK+I6GT0nymoDI0apgQ=' 'sha256-bgDQPJcuRzGf2J+/PjvmNhc0EhDYBMNKYJaAbTnoVSM=' 'sha256-j7860xPExEBHYmkcJp1gb63TzQQQOMs4l2wKco28Ils=' 'sha256-kjhYp0l1gvha4rONirWHZeoKDrYMng3hYiZ86UFk9Ls=' 'sha256-nLuq/ZovWdcDwGBaqOP8RehYvRDs15tlaxc+ASDtO2Y=' 'sha256-piKn/BMciMMX+j1n/XDhoTDVzdtV0nfAoYOn/FMWBPA=' 'sha256-trVyIpoPg+HMqd7mrBPkTowWQe9HNLuzZ2MG4Lw+fcY=' 'sha256-w4Euu9hwZiKURm9SwGeCAAlP4aaRbDLJDlfRg6dg6ow=' 'sha256-yJdJWUO91yHebJzNc8q4f3STMry5vR/OO3oZ0LWnaJg=' 'sha256-zSXKP3mOIJV8wFcGXyB2fD+FpZ7xGCriy9ociEU81W4=' 'sha256-zlnl3okIlL6j+kdPCOKcBQ2NL1N0NqLiLAHoVygfkqc=' 'sha256-zrsy1XcNzoxQgnPbPoC5+ncv2DCQ2B1tEEyci9Y5dLs='; style-src 'self' 'unsafe-inline'; img-src 'self' data: https:; font-src 'self' data:; connect-src 'self' https: wss:; media-src 'self' https:; worker-src 'self' blob:; child-src blob: https://*.elevenlabs.io https://*.daily.co https://challenges.cloudflare.com https://js.stripe.com; frame-src https://*.elevenlabs.io https://*.daily.co https://challenges.cloudflare.com https://js.stripe.com https://mc.yandex.ru https://mc.yandex.net https://mc.yandex.com; frame-ancestors 'none'; base-uri 'self'; form-action 'self' https://visa2au.mmportal.cloud; upgrade-insecure-requests`;

export const onRequest: PagesFunction = async ({ request, next }) => {
  const res = await next();
  const ct = res.headers.get("content-type") || "";
  if (!ct.includes("text/html")) return res; // CSP only matters for documents
  const r = new Response(res.body, res);
  r.headers.set("Content-Security-Policy", CSP);
  return r;
};
