# -*- coding: utf-8 -*-
# French translation map for app/visas.html and app/team.html (Visa2AU)
# Keys are EXACT substrings as they appear in the source files (HTML entities preserved).
# Non-translated items (brand, MARN, subclass numbers, AUD, codes, names, addresses) are deliberately omitted.
# WARNING: short keys "Visa", "Services", "Team" are substring-hazardous ("Visa2AU", "Our Team").
# Apply keys in DESCENDING length order and protect "Visa2AU" with a placeholder before replacing "Visa".

FR_TITLE = "Services de visas | Tous les types de visas australiens | Visa2AU"
FR_DESC = "Services d'immigration complets couvrant toutes les principales catégories de visas australiens : partenaire, qualifié, parrainé par l'employeur, étudiant, visiteur, parent et protection."

FR_MAP = {
    # ---- <head> titles & meta descriptions (both pages) ----
    "Visa Services | All Australian Visa Types | Visa2AU": "Services de visas | Tous les types de visas australiens | Visa2AU",
    "Comprehensive immigration services covering all major Australian visa categories: partner, skilled, employer-sponsored, student, visitor, parent and protection visas.": "Services d'immigration complets couvrant toutes les principales catégories de visas australiens : partenaire, qualifié, parrainé par l'employeur, étudiant, visiteur, parent et protection.",
    "Our Team — MARN Registered Migration Agents | Visa2AU": "Notre équipe — agents de migration enregistrés MARN | Visa2AU",
    "Meet the Visa2AU team: MARN-registered migration agents with 20+ years of experience in Australian immigration law, based in North Sydney.": "Rencontrez l'équipe Visa2AU : des agents de migration enregistrés MARN avec plus de 20 ans d'expérience en droit de l'immigration australien, basés à North Sydney.",
    # ---- visas.html: hero ----
    "Visa": "Services de",
    "Services": "visas",
    "Every visa hub includes a journey map, transparent costs, eligibility detail and answers — because informed clients make stronger applications.": "Chaque page de visa comprend une feuille de route, des coûts transparents, les détails d'éligibilité et des réponses — car des clients bien informés déposent des demandes plus solides.",
    # ---- filters ----
    "All": "Tous",
    "Family": "Famille",
    "Skilled": "Qualifié",
    "Employer": "Employeur",
    "Student": "Étudiant",
    "Visitor": "Visiteur",
    "Other": "Autre",
    "Popular": "Populaire",
    "Filter by category": "Filtrer par catégorie",
    # ---- visa cards (names, taglines, processing) ----
    "Partner Visas": "Visas partenaires",
    "For partners of Australian citizens, PR holders or eligible NZ citizens.": "Pour les partenaires de citoyens australiens, résidents permanents ou citoyens NZ éligibles.",
    "12–24 months (typical)": "12–24 mois (en moyenne)",
    "Details →": "Détails →",
    "Partner Visa (Offshore)": "Visa partenaire (offshore)",
    "Apply from outside Australia, then settle permanently.": "Demande hors d'Australie, puis installation permanente.",
    "Prospective Marriage Visa": "Visa mariage projeté",
    "Come to Australia to marry your fiancé(e).": "Venir en Australie pour épouser votre fiancé(e).",
    "12–18 months (typical)": "12–18 mois (en moyenne)",
    "Visitor Visa": "Visa visiteur",
    "Tourist and business visitor streams.": "Volets touristique et visiteur d'affaires.",
    "2–4 weeks (typical)": "2–4 semaines (en moyenne)",
    "Student Visa": "Visa étudiant",
    "Study at Australian schools, colleges and universities.": "Étudier dans les écoles, collèges et universités australiens.",
    "4–8 weeks (typical)": "4–8 semaines (en moyenne)",
    "Work &amp; Holiday Visas": "Visas vacances-travail",
    "Work and travel Australia for young adults.": "Travail et voyage en Australie pour les jeunes adultes.",
    "2–6 weeks (typical)": "2–6 semaines (en moyenne)",
    "Training Visa": "Visa formation professionnelle",
    "Structured workplace training and professional development.": "Formation en entreprise structurée et développement professionnel.",
    "3–6 months (typical)": "3–6 mois (en moyenne)",
    "Short Stay Specialist": "Spécialiste court séjour",
    "Highly specialised short-term work.": "Travail hautement spécialisé de courte durée.",
    "2–8 weeks (stream dependent)": "2–8 semaines (selon le volet)",
    "Skills in Demand (SID)": "Compétences en demande (SID)",
    "Employer-sponsored work visa — the TSS successor.": "Visa de travail parrainé par l'employeur — successeur du TSS.",
    "2–4 months (accredited sponsors faster)": "2–4 mois (plus rapide pour les parrains accrédités)",
    "Skilled Employer Sponsored Regional": "Visa régional parrainé",
    "Regional sponsorship with a PR pathway — incl. DAMA concessions.": "Parrainage régional avec voie RP — y compris concessions DAMA.",
    "Employer Nomination Scheme": "Schéma de nomination par l'employeur (ENS)",
    "Permanent residency through employer nomination.": "Résidence permanente par nomination d'employeur.",
    "6–12 months (typical)": "6–12 mois (en moyenne)",
    "Skilled Independent &amp; State Nominated": "Indépendant &amp; nominé par un État",
    "Points-tested permanent residency — no sponsor needed.": "Résidence permanente à points — sans parrain.",
    "6–12 months after invitation": "6–12 mois après l'invitation",
    "Parent Visas": "Visas parents",
    "Reunite with your parents — standard, contributory and sponsored streams.": "Retrouver vos parents — volets standard, contributif et parrainé.",
    "103: 20+ years queue · Contributory: 6–12 years · 870: 3–6 months": "103 : file d'attente 20+ ans · Contributif : 6–12 ans · 870 : 3–6 mois",
    "Skills Assessments": "Évaluations des compétences",
    "Get your qualifications recognised for skilled migration.": "Faire reconnaître vos qualifications pour la migration qualifiée.",
    "8–16 weeks (authority dependent)": "8–16 semaines (selon l'organisme)",
    "Australian Citizenship": "Citoyenneté australienne",
    "The final step in your migration journey.": "La dernière étape de votre parcours migratoire.",
    "4–8 months (conferral, typical)": "4–8 mois (conferral, en moyenne)",
    "Visa Refusals &amp; ART Appeals": "Refus de visa &amp; recours ART",
    "Refused, cancelled, or facing a deadline? Act fast.": "Refus, annulation ou délai serré ? Agissez vite.",
    "Deadlines: usually 21–28 days to lodge · Review: 6–18 months": "Délais : généralement 21–28 jours pour déposer · Réexamen : 6–18 mois",
    "Bridging Visas": "Visas de transition",
    "Keep your status lawful between visas.": "Garder un statut régulier entre deux visas.",
    "Usually granted automatically with the linked application": "Généralement accordé automatiquement avec la demande liée",
    "Protection Visa": "Visa de protection",
    "Protection claims handled with care and confidentiality.": "Demandes de protection traitées avec soin et confidentialité.",
    "Varies widely; often 12+ months": "Varie fortement ; souvent 12+ mois",
    "Urgent": "Urgent",
    "Urgent Visa Help": "Aide visa urgente",
    "Strict deadlines — some as short as 7 days. What to do and how fast, step by step.": "Des délais stricts — certains de seulement 7 jours. Que faire et à quelle vitesse, étape par étape.",
    "Act within days": "Agir sous quelques jours",
    "Get help →": "Obtenir de l'aide →",
    # ---- wizard section ----
    "Visa Pathway Finder": "Assistant de choix de visa",
    "Not sure which visa fits?": "Vous ne savez pas quel visa choisir ?",
    "Answer a few questions and we'll tailor the visa options to you — with the reasoning behind each match, indicative costs and processing times.": "Répondez à quelques questions et nous adapterons les options de visa à votre profil — avec le raisonnement derrière chaque suggestion, des coûts indicatifs et des délais de traitement.",
    "Question": "Question",
    "of": "sur",
    "← Back": "← Retour",
    "Your realistic pathways": "Vos parcours réalistes",
    "Each match shows the reasoning from your answers. Indicative only — migration law is complex and individual; a consultation confirms your actual options.": "Chaque suggestion montre le raisonnement issu de vos réponses. À titre indicatif uniquement — le droit de la migration est complexe et individuel ; une consultation confirmera vos options réelles.",
    "Discuss My Case →": "Discuter de mon dossier →",
    "Start over": "Recommencer",
    "Ready to discuss your case?": "Prêt à discuter de votre dossier ?",
    "Book a consultation with a MARN-registered migration agent — strategy first, fixed fee quoted upfront.": "Réservez une consultation avec un agent de migration enregistré MARN — la stratégie d'abord, honoraires fixes annoncés à l'avance.",
    "Book a consultation →": "Réserver une consultation →",
    "Detailed Visa Assessment": "Évaluation de visa détaillée",
    # ---- wizard questions / options / why (JSON) ----
    "What best describes your situation?": "Quelle est la meilleure description de votre situation ?",
    "Every visa belongs to a program stream — family, skilled, employer, student or visitor. This first answer sets the stream; the next questions refine it.": "Chaque visa appartient à un volet de programme — famille, qualifié, employeur, étudiant ou visiteur. Cette première réponse détermine le volet ; les questions suivantes l'affinent.",
    "My partner is Australian / lives in Australia": "Mon partenaire est australien / vit en Australie",
    "I have skills or qualifications Australia needs": "J'ai des compétences ou qualifications dont l'Australie a besoin",
    "An Australian employer wants to hire/sponsor me": "Un employeur australien veut m'embaucher/me parrainer",
    "I want to study in Australia": "Je veux étudier en Australie",
    "I want to visit, or a working holiday": "Je veux visiter l'Australie ou faire un séjour vacances-travail",
    "I want to bring my parents or family": "Je veux faire venir mes parents ou ma famille",
    "Where are you right now?": "Où êtes-vous actuellement ?",
    "Onshore and offshore applications use different visa streams (for example partner 820/801 onshore vs 309/100 offshore) and different bridging options — this changes the recommendation, not just the paperwork.": "Les demandes onshore et offshore utilisent des volets de visa différents (par exemple partenaire 820/801 onshore vs 309/100 offshore) et des options de transition différentes — cela change la recommandation, pas seulement la paperasse.",
    "Outside Australia": "Hors d'Australie",
    "Inside Australia (on any visa)": "En Australie (sous n'importe quel visa)",
    "Your age range?": "Votre tranche d'âge ?",
    "Age is a legal criterion, not a detail: most skilled visas close at 45, working holiday visas at 30–35, and points for age change every few years. It can make or rule out entire pathways.": "L'âge est un critère juridique, pas un détail : la plupart des visas qualifiés ferment à 45 ans, les visas vacances-travail à 30–35 ans, et les points d'âge changent tous les quelques années. Cela peut ouvrir ou exclure des parcours entiers.",
    "Under 30": "Moins de 30 ans",
    "45 or over": "45 ans et plus",
    "Do you have a skilled occupation or trade?": "Avez-vous une profession qualifiée ou un métier ?",
    "Skilled visas are built around occupation lists and skills assessments. A listed trade or profession opens independent and sponsored pathways; without one, we look at family, study or employer routes instead.": "Les visas qualifiés reposent sur les listes de métiers et les évaluations des compétences. Un métier ou une profession listé(e) ouvre des parcours indépendants et parrainés ; à défaut, nous examinons les voies familiales, étudiantes ou employeur.",
    "Yes — a trade (chef, carpenter, electrician…)": "Oui — un métier (cuisinier, charpentier, électricien…)",
    "Yes — a profession (IT, engineering, teaching…)": "Oui — une profession (IT, ingénierie, enseignement…)",
    "I work, but not in a listed occupation": "Je travaille, mais pas dans un métier listé",
    "No / not applicable": "Non / sans objet",
    "Your English level?": "Votre niveau d'anglais ?",
    "English test scores are worth up to 20 skilled points and are a hard requirement for most work visas — but some DAMA and family pathways are more flexible. An honest answer here keeps the recommendation realistic.": "Les scores des tests d'anglais valent jusqu'à 20 points et sont une exigence stricte pour la plupart des visas de travail — mais certains parcours DAMA et familiaux sont plus flexibles. Une réponse honnête ici garde la recommandation réaliste.",
    "Fluent / native-like": "Courant / quasi natif",
    "Good working English": "Bon anglais professionnel",
    "Basic — I would need to improve": "Basique — je devrais progresser",
    "Would you consider living outside Sydney, Melbourne or Brisbane?": "Envisageriez-vous de vivre hors de Sydney, Melbourne ou Brisbane ?",
    "Regional Australia offers the widest door: extra points, a broader occupation list, DAMA concessions on English/salary/age, and priority processing. For many applicants it is the fastest realistic route to PR.": "L'Australie régionale offre la porte la plus large : points supplémentaires, liste de métiers élargie, concessions DAMA sur l'anglais/salaire/âge et traitement prioritaire. Pour beaucoup, c'est la voie la plus rapide et réaliste vers la RP.",
    "Yes — regional life appeals to me": "Oui — la vie régionale m'attire",
    "Maybe — if it improves my chances": "Peut-être — si cela améliore mes chances",
    "No — major cities only": "Non — grandes villes uniquement",
    "When do you want to move?": "Quand souhaitez-vous déménager ?",
    "Some pathways take years (parent queues, invitation rounds), others weeks (visitor visas). Your timeframe tells us whether to plan a direct route or a staged strategy.": "Certains parcours prennent des années (files d'attente parents, tours d'invitation), d'autres des semaines (visas visiteur). Votre calendrier nous indique s'il faut planifier une voie directe ou une stratégie par étapes.",
    "As soon as possible": "Dès que possible",
    "Within 6–12 months": "Dans 6–12 mois",
    "I'm planning 1–3 years ahead": "Je prévois d'ici 1 à 3 ans",
    # ---- visa-meta JSON taglines (no trailing period) ----
    "For partners of Australian citizens, PR holders or eligible NZ citizens": "Pour les partenaires de citoyens australiens, résidents permanents ou citoyens NZ éligibles",
    "Apply from outside Australia, then settle permanently": "Demande hors d'Australie, puis installation permanente",
    "Come to Australia to marry your fiancé(e)": "Venir en Australie pour épouser votre fiancé(e)",
    "Tourist and business visitor streams": "Volets touristique et visiteur d'affaires",
    "Study at Australian schools, colleges and universities": "Étudier dans les écoles, collèges et universités australiens",
    "Work & Holiday Visas": "Visas vacances-travail",
    "Work and travel Australia for young adults": "Travail et voyage en Australie pour les jeunes adultes",
    "Structured workplace training and professional development": "Formation en entreprise structurée et développement professionnel",
    "Highly specialised short-term work": "Travail hautement spécialisé de courte durée",
    "Employer-sponsored work visa — the TSS successor": "Visa de travail parrainé par l'employeur — successeur du TSS",
    "Regional sponsorship with a PR pathway — incl. DAMA concessions": "Parrainage régional avec voie RP — y compris concessions DAMA",
    "Permanent residency through employer nomination": "Résidence permanente par nomination d'employeur",
    "Skilled Independent & State Nominated": "Indépendant & nommé par un État",
    "Points-tested permanent residency — no sponsor needed": "Résidence permanente à points — sans parrain",
    "Reunite with your parents — standard, contributory and sponsored streams": "Retrouver vos parents — volets standard, contributif et parrainé",
    "Get your qualifications recognised for skilled migration": "Faire reconnaître vos qualifications pour la migration qualifiée",
    "The final step in your migration journey": "La dernière étape de votre parcours migratoire",
    "Visa Refusals & ART Appeals": "Refus de visa & recours ART",
    "Refused, cancelled, or facing a deadline? Act fast": "Refus, annulation ou délai serré ? Agissez vite",
    "Keep your status lawful between visas": "Garder un statut régulier entre deux visas",
    "Protection claims handled with care and confidentiality": "Demandes de protection traitées avec soin et confidentialité",
    # ---- visa-meta fees (translatable parts only) ----
    "From AUD 11,710 (main applicant)": "À partir de 11 710 AUD (demandeur principal)",
    "From AUD 11,710": "À partir de 11 710 AUD",
    "From AUD 250 (offshore)": "À partir de 250 AUD (offshore)",
    "From AUD 2,500": "À partir de 2 500 AUD",
    "From AUD 650": "À partir de 650 AUD",
    "From AUD 415": "À partir de 415 AUD",
    "From AUD 415 (400) / AUD 415 (408)": "À partir de 415 AUD (400) / 415 AUD (408)",
    "From AUD 3,210 (Core/Specialist, main applicant)": "À partir de 3 210 AUD (Core/Specialist, demandeur principal)",
    "From AUD 4,910 (main applicant)": "À partir de 4 910 AUD (demandeur principal)",
    "103: from AUD 7,055 · 143: staged contributory charges · 870: from AUD 1,145": "103 : à partir de 7 055 AUD · 143 : frais contributifs par étapes · 870 : à partir de 1 145 AUD",
    "AUD 500–3,000+ (authority dependent)": "500–3 000+ AUD (selon l'organisme)",
    "From AUD 575 (conferral)": "À partir de 575 AUD (conferral)",
    "ART fee: AUD 3,496 (refundable 50% if successful, exemptions exist)": "Frais ART : 3 496 AUD (50 % remboursés en cas de succès, exonérations possibles)",
    "No charge (linked grant)": "Gratuit (octroi lié)",
    "From AUD 45": "À partir de 45 AUD",
    "$3,300 AUD (employee side)": "3 300 AUD (côté employé)",
    "$5,500 AUD (employee side)": "5 500 AUD (côté employé)",
    "From $1,100 AUD": "À partir de 1 100 AUD",
    # ---- wizard results (JS strings) ----
    "Why we ask: ": "Pourquoi cette question : ",
    "Strongest match": "Meilleure correspondance",
    "Good match": "Bonne correspondance",
    "Worth exploring": "À explorer",
    "Why some options are missing": "Pourquoi certaines options sont absentes",
    "· Gov: ": "· Frais publics : ",
    "· Professional: ": "· Honoraires : ",
    "(indicative)": "(indicatif)",
    "matches your situation": "correspond à votre situation",
    "you would apply from outside Australia": "vous déposeriez votre demande hors d'Australie",
    "you are already in Australia": "vous êtes déjà en Australie",
    "regional and DAMA routes can allow age concessions": "les voies régionales et DAMA peuvent accorder des concessions d'âge",
    "your age keeps working holiday options open": "votre âge laisse ouvertes les options vacances-travail",
    "age gives you maximum skilled points": "votre âge vous donne le maximum de points",
    "trades are in strong demand for employer sponsorship": "les métiers sont très demandés pour le parrainage employeur",
    "regional lists cover most trades": "les listes régionales couvrent la plupart des métiers",
    "your trade will need a skills assessment": "votre métier nécessitera une évaluation des compétences",
    "professional occupations suit points-tested visas": "les professions conviennent aux visas à points",
    "a positive skills assessment is step one": "une évaluation positive des compétences est la première étape",
    "strong English adds valuable points": "un bon niveau d'anglais ajoute des points précieux",
    "DAMA concessions may allow lower English": "les concessions DAMA peuvent accepter un anglais plus faible",
    "you are open to regional Australia — the widest door": "vous êtes ouvert à l'Australie régionale — la porte la plus large",
    "regional routes could improve your chances": "les voies régionales pourraient améliorer vos chances",
    "fastest lawful way to travel while planning": "le moyen légal le plus rapide de voyager pendant la planification",
    "you have time to build points and documents": "vous avez le temps d'accumuler des points et des documents",
    "parent queues reward early planning": "les files d'attente parents récompensent une planification précoce",
    "Independent skilled visas (189/190) generally close at 45 — which is why regional, DAMA or employer routes appear instead.": "Les visas qualifiés indépendants (189/190) ferment généralement à 45 ans — c'est pourquoi des voies régionales, DAMA ou employeur apparaissent à la place.",
    "Working holiday visas are age-limited (usually 30, or 35 for some passports) — a Visitor visa 600 is the flexible option.": "Les visas vacances-travail sont limités par l'âge (généralement 30 ans, ou 35 pour certains passeports) — le visa visiteur 600 est l'option flexible.",
    "Independent points-tested visas need strong English; improving your score may reopen them — we can plan for that.": "Les visas indépendants à points exigent un bon niveau d'anglais ; améliorer votre score peut les rouvrir — nous pouvons le planifier.",
    # ---- team.html ----
    "Meet Our": "Notre",
    "Team": "équipe",
    "Simplifying Australian immigration since 2004 — with 2,000+ cases handled and a 99.8% success rate.": "Nous simplifions l'immigration australienne depuis 2004 — plus de 2 000 dossiers traités et un taux de réussite de 99,8 %.",
    "Principal Migration Agent": "Agent de migration principal",
    "Founder of Visa2AU with over 20 years in Australian immigration law. Specialises in complex partner cases, refusals and ART appeals. NAATI-certified translator (Russian).": "Fondateur de Visa2AU avec plus de 20 ans d'expérience en droit de l'immigration australien. Spécialiste des dossiers partenaires complexes, des refus et des recours ART. Traducteur certifié NAATI (russe).",
    "Registered Migration Agent": "Agent de migration enregistré",
    "Focuses on employer-sponsored programs (482/494/186), DAMA arrangements and skilled migration. Known for meticulous documentation and honest prospects assessments.": "Se concentre sur les programmes parrainés par l'employeur (482/494/186), les accords DAMA et la migration qualifiée. Reconnu pour sa documentation méticuleuse et ses évaluations honnêtes des chances.",
    "Client Coordination": "Coordination client",
    "Case management &amp; coordination": "Gestion et coordination des dossiers",
    "Coordinates casework from first instruction to lodgement, keeping clients, employers and authorities aligned at every step.": "Coordonne le travail sur les dossiers de la première instruction au dépôt, en gardant clients, employeurs et autorités alignés à chaque étape.",
    "Administration Support, Client Coordination": "Soutien administratif, coordination client",
    "Multilingual support EN/RU": "Soutien multilingue EN/RU",
    "Keeps the office running and supports client coordination — organising consultations, assessments and document checklists, in English and Russian.": "Assure le fonctionnement du bureau et soutient la coordination client — en organisant consultations, évaluations et listes de documents, en anglais et en russe.",
    "Our Values": "Nos valeurs",
    "Values &amp;": "Valeurs et",
    "social responsibility": "responsabilité sociale",
    "Integrity &amp; transparency": "Intégrité et transparence",
    "Honest, evidence-based advice. We never promise outcomes we cannot deliver — and you understand the realistic prospects of your case before proceeding.": "Des conseils honnêtes et fondés sur des preuves. Nous ne promettons jamais des résultats que nous ne pouvons pas atteindre — et vous comprenez les chances réelles de votre dossier avant de commencer.",
    "Social responsibility": "Responsabilité sociale",
    "We believe in giving back. In select cases we undertake pro bono work for people in genuine need — including victims of domestic violence and those facing humanitarian crises.": "Nous croyons à l'engagement. Dans certains cas, nous faisons du travail pro bono pour des personnes réellement dans le besoin — notamment les victimes de violences domestiques et celles confrontées à des crises humanitaires.",
    "Client dedication": "Dévouement au client",
    "Every case receives our full attention. Immigration decisions shape lives, families and futures — we treat yours with the seriousness and compassion it deserves.": "Chaque dossier reçoit toute notre attention. Les décisions d'immigration façonnent des vies, des familles et des avenirs — nous traitons le vôtre avec le sérieux et la compassion qu'il mérite.",
    "Continuous learning": "Formation continue",
    "Immigration law changes frequently. Our agents maintain continuous professional development so our advice reflects the latest legislation, policy and case law.": "Le droit de l'immigration change souvent. Nos agents assurent un développement professionnel continu afin que nos conseils reflètent la législation, la politique et la jurisprudence les plus récentes.",
    "Excellence in service": "Excellence du service",
    "Excellence in every aspect of our work — from document preparation to communication with the Department. Our goal: give every application its best possible chance.": "L'excellence dans chaque aspect de notre travail — de la préparation des documents à la communication avec le Département. Notre objectif : donner à chaque demande sa meilleure chance.",
    "Multicultural understanding": "Compréhension multiculturelle",
    "Our team speaks English and Russian and works with clients from diverse backgrounds. We understand the challenges migrants face — and provide culturally sensitive service.": "Notre équipe parle anglais et russe et travaille avec des clients de divers horizons. Nous comprenons les défis des migrants — et offrons un service culturellement adapté.",
    "About Visa2AU": "À propos de Visa2AU",
    "Visa2AU Pty Ltd has guided individuals, families and employers through Australian immigration since 2004. From our North Sydney office we serve clients across Australia and worldwide — in English and Russian — with transparent fixed-fee pricing and a simple promise: honest advice about your prospects before you spend a dollar.": "Visa2AU Pty Ltd accompagne particuliers, familles et employeurs dans l'immigration australienne depuis 2004. Depuis notre bureau de North Sydney, nous servons des clients dans toute l'Australie et dans le monde — en anglais et en russe — avec des tarifs fixes transparents et une promesse simple : des conseils honnêtes sur vos chances avant que vous dépensiez un dollar.",
    "Natasha Arens, Principal Migration Agent at Visa2AU": "Natasha Arens, agent de migration principal chez Visa2AU",
    "Denis, Client Coordination at Visa2AU": "Denis, coordination client chez Visa2AU",
    "Franz, Administration Support, Client Coordination at Visa2AU": "Franz, soutien administratif et coordination client chez Visa2AU",
}
