# -*- coding: utf-8 -*-
# Russian translation map for app/visas.html and app/team.html (Visa2AU)
# Keys are EXACT substrings as they appear in the source files (HTML entities preserved).
# Non-translated items (brand, MARN, subclass numbers, AUD, codes, names, addresses) are deliberately omitted.
# WARNING: short keys "Visa", "Services", "Team" are substring-hazardous ("Visa2AU", "Our Team").
# Apply keys in DESCENDING length order and protect "Visa2AU" with a placeholder before replacing "Visa".

RU_TITLE = "Визовые услуги | Все типы австралийских виз | Visa2AU"
RU_DESC = "Комплексные иммиграционные услуги по всем основным категориям австралийских виз: партнёрские, квалифицированные, спонсируемые работодателем, студенческие, гостевые, родительские и защитные."

RU_MAP = {
    # ---- <head> titles & meta descriptions (both pages) ----
    "Visa Services | All Australian Visa Types | Visa2AU": "Визовые услуги | Все типы австралийских виз | Visa2AU",
    "Comprehensive immigration services covering all major Australian visa categories: partner, skilled, employer-sponsored, student, visitor, parent and protection visas.": "Комплексные иммиграционные услуги по всем основным категориям австралийских виз: партнёрские, квалифицированные, спонсируемые работодателем, студенческие, гостевые, родительские и защитные.",
    "Our Team — MARN Registered Migration Agents | Visa2AU": "Наша команда — зарегистрированные миграционные агенты MARN | Visa2AU",
    "Meet the Visa2AU team: MARN-registered migration agents with 20+ years of experience in Australian immigration law, based in North Sydney.": "Познакомьтесь с командой Visa2AU: зарегистрированные миграционные агенты MARN с более чем 20-летним опытом в австралийском иммиграционном праве, базирующиеся в North Sydney.",
    # ---- visas.html: hero ----
    "Visa": "Визовые",
    "Services": "услуги",
    "Every visa hub includes a journey map, transparent costs, eligibility detail and answers — because informed clients make stronger applications.": "Каждый визовый хаб включает карту маршрута, прозрачные цены, детали требований и ответы на вопросы — потому что информированные клиенты подают более сильные заявления.",
    # ---- filters ----
    "All": "Все",
    "Family": "Семейные",
    "Skilled": "Квалифицированные",
    "Employer": "Работодатель",
    "Student": "Студенческие",
    "Visitor": "Гостевые",
    "Other": "Другие",
    "Popular": "Популярные",
    "Filter by category": "Фильтр по категории",
    # ---- visa cards (names, taglines, processing) ----
    "Partner Visas": "Визы партнёров",
    "For partners of Australian citizens, PR holders or eligible NZ citizens.": "Для партнёров граждан Австралии, постоянных резидентов или eligible-граждан Новой Зеландии.",
    "12–24 months (typical)": "12–24 месяца (обычно)",
    "Details →": "Подробнее →",
    "Partner Visa (Offshore)": "Виза партнёра (оффшор)",
    "Apply from outside Australia, then settle permanently.": "Подача за пределами Австралии с последующим постоянным поселением.",
    "Prospective Marriage Visa": "Виза жениха/невесты",
    "Come to Australia to marry your fiancé(e).": "Приехать в Австралию, чтобы вступить в брак с женихом/невестой.",
    "12–18 months (typical)": "12–18 месяцев (обычно)",
    "Visitor Visa": "Гостевая виза",
    "Tourist and business visitor streams.": "Туристические и деловые гостевые потоки.",
    "2–4 weeks (typical)": "2–4 недели (обычно)",
    "Student Visa": "Студенческая виза",
    "Study at Australian schools, colleges and universities.": "Учёба в австралийских школах, колледжах и университетах.",
    "4–8 weeks (typical)": "4–8 недель (обычно)",
    "Work &amp; Holiday Visas": "Визы «работа и отдых»",
    "Work and travel Australia for young adults.": "Работа и путешествия по Австралии для молодёжи.",
    "2–6 weeks (typical)": "2–6 недель (обычно)",
    "Training Visa": "Виза профессионального обучения",
    "Structured workplace training and professional development.": "Структурированное обучение на рабочем месте и профессиональное развитие.",
    "3–6 months (typical)": "3–6 месяцев (обычно)",
    "Short Stay Specialist": "Краткосрочные специалисты",
    "Highly specialised short-term work.": "Высокоспециализированная краткосрочная работа.",
    "2–8 weeks (stream dependent)": "2–8 недель (зависит от потока)",
    "Skills in Demand (SID)": "Востребованные навыки (SID)",
    "Employer-sponsored work visa — the TSS successor.": "Рабочая виза по спонсорству работодателя — преемница TSS.",
    "2–4 months (accredited sponsors faster)": "2–4 месяца (для аккредитованных спонсоров быстрее)",
    "Skilled Employer Sponsored Regional": "Региональная спонсируемая",
    "Regional sponsorship with a PR pathway — incl. DAMA concessions.": "Региональное спонсорство с путём к PR — включая послабления DAMA.",
    "Employer Nomination Scheme": "Схема номинации работодателя (ENS)",
    "Permanent residency through employer nomination.": "Постоянное резидентство через номинацию работодателя.",
    "6–12 months (typical)": "6–12 месяцев (обычно)",
    "Skilled Independent &amp; State Nominated": "Независимая и номинируемая штатом",
    "Points-tested permanent residency — no sponsor needed.": "Постоянное резидентство по балльной системе — без спонсора.",
    "6–12 months after invitation": "6–12 месяцев после приглашения",
    "Parent Visas": "Родительские визы",
    "Reunite with your parents — standard, contributory and sponsored streams.": "Воссоединение с родителями — стандартные, взносовые (contributory) и спонсируемые потоки.",
    "103: 20+ years queue · Contributory: 6–12 years · 870: 3–6 months": "103: очередь 20+ лет · Contributory: 6–12 лет · 870: 3–6 месяцев",
    "Skills Assessments": "Подтверждение квалификации",
    "Get your qualifications recognised for skilled migration.": "Признание вашей квалификации для квалифицированной миграции.",
    "8–16 weeks (authority dependent)": "8–16 недель (зависит от органа)",
    "Australian Citizenship": "Гражданство Австралии",
    "The final step in your migration journey.": "Финальный шаг вашего миграционного пути.",
    "4–8 months (conferral, typical)": "4–8 месяцев (conferral, обычно)",
    "Visa Refusals &amp; ART Appeals": "Отказы и апелляции в ART",
    "Refused, cancelled, or facing a deadline? Act fast.": "Отказ, аннулирование или жёсткий дедлайн? Действуйте быстро.",
    "Deadlines: usually 21–28 days to lodge · Review: 6–18 months": "Сроки: обычно 21–28 дней на подачу · Пересмотр: 6–18 месяцев",
    "Bridging Visas": "Бриджинг-визы",
    "Keep your status lawful between visas.": "Сохраняйте легальный статус между визами.",
    "Usually granted automatically with the linked application": "Обычно выдаётся автоматически вместе со связанным заявлением",
    "Protection Visa": "Защитная виза",
    "Protection claims handled with care and confidentiality.": "Заявления о защите — бережно и конфиденциально.",
    "Varies widely; often 12+ months": "Сильно варьируется; часто 12+ месяцев",
    "Urgent": "Срочно",
    "Urgent Visa Help": "Срочная помощь по визе",
    "Strict deadlines — some as short as 7 days. What to do and how fast, step by step.": "Строгие дедлайны — некоторые всего 7 дней. Что делать и насколько быстро, шаг за шагом.",
    "Act within days": "Действуйте в течение дней",
    "Get help →": "Получить помощь →",
    # ---- wizard section ----
    "Visa Pathway Finder": "Подбор визового маршрута",
    "Not sure which visa fits?": "Не знаете, какая виза подходит?",
    "Answer a few questions and we'll tailor the visa options to you — with the reasoning behind each match, indicative costs and processing times.": "Ответьте на несколько вопросов, и мы подберём варианты виз под вас — с объяснением каждого совпадения, ориентировочными ценами и сроками.",
    "Question": "Вопрос",
    "of": "из",
    "← Back": "← Назад",
    "Your realistic pathways": "Ваши реалистичные маршруты",
    "Each match shows the reasoning from your answers. Indicative only — migration law is complex and individual; a consultation confirms your actual options.": "Каждое совпадение показывает логику, основанную на ваших ответах. Только ориентировочно — миграционное право сложно и индивидуально; консультация подтвердит ваши реальные варианты.",
    "Discuss My Case →": "Обсудить мой случай →",
    "Start over": "Начать заново",
    "Ready to discuss your case?": "Готовы обсудить ваш случай?",
    "Book a consultation with a MARN-registered migration agent — strategy first, fixed fee quoted upfront.": "Запишитесь на консультацию к зарегистрированному миграционному агенту MARN — сначала стратегия, фиксированная цена названа заранее.",
    "Book a consultation →": "Записаться на консультацию →",
    "Detailed Visa Assessment": "Детальная оценка визы",
    # ---- wizard questions / options / why (JSON) ----
    "What best describes your situation?": "Что лучше всего описывает вашу ситуацию?",
    "Every visa belongs to a program stream — family, skilled, employer, student or visitor. This first answer sets the stream; the next questions refine it.": "Каждая виза относится к программному потоку — семейные, квалифицированные, работодательские, студенческие или гостевые. Этот первый ответ задаёт поток; следующие вопросы его уточняют.",
    "My partner is Australian / lives in Australia": "Мой партнёр — гражданин Австралии / живёт в Австралии",
    "I have skills or qualifications Australia needs": "У меня есть навыки или квалификация, в которых нуждается Австралия",
    "An Australian employer wants to hire/sponsor me": "Австралийский работодатель хочет нанять/спонсировать меня",
    "I want to study in Australia": "Я хочу учиться в Австралии",
    "I want to visit, or a working holiday": "Я хочу посетить Австралию или поехать «работать и отдыхать»",
    "I want to bring my parents or family": "Я хочу привезти родителей или семью",
    "Where are you right now?": "Где вы сейчас находитесь?",
    "Onshore and offshore applications use different visa streams (for example partner 820/801 onshore vs 309/100 offshore) and different bridging options — this changes the recommendation, not just the paperwork.": "Заявки onshore и offshore используют разные визовые потоки (например, партнёрская 820/801 onshore против 309/100 offshore) и разные бриджинг-варианты — это меняет рекомендацию, а не только документы.",
    "Outside Australia": "За пределами Австралии",
    "Inside Australia (on any visa)": "Внутри Австралии (по любой визе)",
    "Your age range?": "Ваш возрастной диапазон?",
    "Age is a legal criterion, not a detail: most skilled visas close at 45, working holiday visas at 30–35, and points for age change every few years. It can make or rule out entire pathways.": "Возраст — юридический критерий, а не деталь: большинство квалифицированных виз закрывается в 45, визы «работа и отдых» — в 30–35, а баллы за возраст меняются каждые несколько лет. Это может открывать или полностью исключать целые маршруты.",
    "Under 30": "До 30",
    "45 or over": "45 и старше",
    "Do you have a skilled occupation or trade?": "У вас есть квалифицированная профессия или ремесло?",
    "Skilled visas are built around occupation lists and skills assessments. A listed trade or profession opens independent and sponsored pathways; without one, we look at family, study or employer routes instead.": "Квалифицированные визы строятся вокруг списков профессий и подтверждения квалификации (skills assessment). Профессия из списка открывает независимые и спонсируемые маршруты; без неё мы рассматриваем семейные, учебные или работодательские пути.",
    "Yes — a trade (chef, carpenter, electrician…)": "Да — ремесло (повар, плотник, электрик…)",
    "Yes — a profession (IT, engineering, teaching…)": "Да — профессия (IT, инженерия, преподавание…)",
    "I work, but not in a listed occupation": "Я работаю, но не по профессии из списка",
    "No / not applicable": "Нет / не применимо",
    "Your English level?": "Ваш уровень английского?",
    "English test scores are worth up to 20 skilled points and are a hard requirement for most work visas — but some DAMA and family pathways are more flexible. An honest answer here keeps the recommendation realistic.": "Результаты теста по английскому дают до 20 баллов и являются жёстким требованием для большинства рабочих виз — но некоторые маршруты DAMA и семейные потоки более гибкие. Честный ответ здесь делает рекомендацию реалистичной.",
    "Fluent / native-like": "Свободно / как носитель",
    "Good working English": "Хороший рабочий английский",
    "Basic — I would need to improve": "Базовый — мне нужно улучшать",
    "Would you consider living outside Sydney, Melbourne or Brisbane?": "Рассмотрели бы вы жизнь за пределами Сиднея, Мельбурна или Брисбена?",
    "Regional Australia offers the widest door: extra points, a broader occupation list, DAMA concessions on English/salary/age, and priority processing. For many applicants it is the fastest realistic route to PR.": "Региональная Австралия открывает самую широкую дверь: дополнительные баллы, более широкий список профессий, послабления DAMA по английскому/зарплате/возрасту и приоритетная обработка. Для многих заявителей это самый быстрый реалистичный путь к PR.",
    "Yes — regional life appeals to me": "Да — региональная жизнь меня привлекает",
    "Maybe — if it improves my chances": "Возможно — если это повысит мои шансы",
    "No — major cities only": "Нет — только крупные города",
    "When do you want to move?": "Когда вы хотите переехать?",
    "Some pathways take years (parent queues, invitation rounds), others weeks (visitor visas). Your timeframe tells us whether to plan a direct route or a staged strategy.": "Некоторые маршруты занимают годы (родительские очереди, раунды приглашений), другие — недели (гостевые визы). Ваши сроки подскажут нам, планировать прямой маршрут или поэтапную стратегию.",
    "As soon as possible": "Как можно скорее",
    "Within 6–12 months": "В течение 6–12 месяцев",
    "I'm planning 1–3 years ahead": "Я планирую переезд через 1–3 года",
    # ---- visa-meta JSON taglines (no trailing period) ----
    "For partners of Australian citizens, PR holders or eligible NZ citizens": "Для партнёров граждан Австралии, постоянных резидентов или eligible-граждан Новой Зеландии",
    "Apply from outside Australia, then settle permanently": "Подача за пределами Австралии с последующим постоянным поселением",
    "Come to Australia to marry your fiancé(e)": "Приехать в Австралию, чтобы вступить в брак с женихом/невестой",
    "Tourist and business visitor streams": "Туристические и деловые гостевые потоки",
    "Study at Australian schools, colleges and universities": "Учёба в австралийских школах, колледжах и университетах",
    "Work & Holiday Visas": "Визы «работа и отдых»",
    "Work and travel Australia for young adults": "Работа и путешествия по Австралии для молодёжи",
    "Structured workplace training and professional development": "Структурированное обучение на рабочем месте и профессиональное развитие",
    "Highly specialised short-term work": "Высокоспециализированная краткосрочная работа",
    "Employer-sponsored work visa — the TSS successor": "Рабочая виза по спонсорству работодателя — преемница TSS",
    "Regional sponsorship with a PR pathway — incl. DAMA concessions": "Региональное спонсорство с путём к PR — включая послабления DAMA",
    "Permanent residency through employer nomination": "Постоянное резидентство через номинацию работодателя",
    "Skilled Independent & State Nominated": "Независимая и номинируемая штатом",
    "Points-tested permanent residency — no sponsor needed": "Постоянное резидентство по балльной системе — без спонсора",
    "Reunite with your parents — standard, contributory and sponsored streams": "Воссоединение с родителями — стандартные, взносовые (contributory) и спонсируемые потоки",
    "Get your qualifications recognised for skilled migration": "Признание вашей квалификации для квалифицированной миграции",
    "The final step in your migration journey": "Финальный шаг вашего миграционного пути",
    "Visa Refusals & ART Appeals": "Отказы и апелляции в ART",
    "Refused, cancelled, or facing a deadline? Act fast": "Отказ, аннулирование или жёсткий дедлайн? Действуйте быстро",
    "Keep your status lawful between visas": "Сохраняйте легальный статус между визами",
    "Protection claims handled with care and confidentiality": "Заявления о защите — бережно и конфиденциально",
    # ---- visa-meta fees (translatable parts only) ----
    "From AUD 11,710 (main applicant)": "От AUD 11 710 (основной заявитель)",
    "From AUD 11,710": "От AUD 11 710",
    "From AUD 250 (offshore)": "От AUD 250 (оффшор)",
    "From AUD 2,500": "От AUD 2 500",
    "From AUD 650": "От AUD 650",
    "From AUD 415": "От AUD 415",
    "From AUD 415 (400) / AUD 415 (408)": "От AUD 415 (400) / AUD 415 (408)",
    "From AUD 3,210 (Core/Specialist, main applicant)": "От AUD 3 210 (Core/Specialist, основной заявитель)",
    "From AUD 4,910 (main applicant)": "От AUD 4 910 (основной заявитель)",
    "103: from AUD 7,055 · 143: staged contributory charges · 870: from AUD 1,145": "103: от AUD 7 055 · 143: поэтапные взносовые платежи · 870: от AUD 1 145",
    "AUD 500–3,000+ (authority dependent)": "AUD 500–3 000+ (зависит от органа)",
    "From AUD 575 (conferral)": "От AUD 575 (conferral)",
    "ART fee: AUD 3,496 (refundable 50% if successful, exemptions exist)": "Пошлина ART: AUD 3 496 (50% возвращается в случае успеха, возможны освобождения)",
    "No charge (linked grant)": "Без пошлины (выдаётся вместе со связанным заявлением)",
    "From AUD 45": "От AUD 45",
    "$3,300 AUD (employee side)": "$3 300 AUD (со стороны сотрудника)",
    "$5,500 AUD (employee side)": "$5 500 AUD (со стороны сотрудника)",
    "From $1,100 AUD": "От $1 100 AUD",
    # ---- wizard results (JS strings) ----
    "Why we ask: ": "Почему мы спрашиваем: ",
    "Strongest match": "Самое сильное совпадение",
    "Good match": "Хорошее совпадение",
    "Worth exploring": "Стоит рассмотреть",
    "Why some options are missing": "Почему некоторые варианты отсутствуют",
    "· Gov: ": "· Госпошлина: ",
    "· Professional: ": "· Профессиональные услуги: ",
    "(indicative)": "(ориентировочно)",
    "matches your situation": "соответствует вашей ситуации",
    "you would apply from outside Australia": "вы подавали бы заявление за пределами Австралии",
    "you are already in Australia": "вы уже в Австралии",
    "regional and DAMA routes can allow age concessions": "региональные маршруты и DAMA допускают послабления по возрасту",
    "your age keeps working holiday options open": "ваш возраст оставляет открытыми варианты «работа и отдых»",
    "age gives you maximum skilled points": "возраст даёт вам максимум баллов",
    "trades are in strong demand for employer sponsorship": "рабочие специальности пользуются высоким спросом для спонсорства работодателем",
    "regional lists cover most trades": "региональные списки охватывают большинство рабочих специальностей",
    "your trade will need a skills assessment": "вашей специальности потребуется подтверждение квалификации",
    "professional occupations suit points-tested visas": "профессиональные специальности подходят для балльных виз",
    "a positive skills assessment is step one": "положительное подтверждение квалификации — первый шаг",
    "strong English adds valuable points": "сильный английский добавляет ценные баллы",
    "DAMA concessions may allow lower English": "послабления DAMA могут допускать более низкий английский",
    "you are open to regional Australia — the widest door": "вы открыты к региональной Австралии — самая широкая дверь",
    "regional routes could improve your chances": "региональные маршруты могут повысить ваши шансы",
    "fastest lawful way to travel while planning": "самый быстрый законный способ путешествовать, пока идёт планирование",
    "you have time to build points and documents": "у вас есть время накопить баллы и подготовить документы",
    "parent queues reward early planning": "родительские очереди вознаграждают раннее планирование",
    "Independent skilled visas (189/190) generally close at 45 — which is why regional, DAMA or employer routes appear instead.": "Независимые квалифицированные визы (189/190) обычно закрываются в 45 — поэтому вместо них появляются региональные, DAMA или работодательские маршруты.",
    "Working holiday visas are age-limited (usually 30, or 35 for some passports) — a Visitor visa 600 is the flexible option.": "Визы «работа и отдых» ограничены по возрасту (обычно 30, или 35 для некоторых паспортов) — гостевая виза 600 — гибкий вариант.",
    "Independent points-tested visas need strong English; improving your score may reopen them — we can plan for that.": "Независимые балльные визы требуют сильного английского; повышение балла может снова открыть их — мы можем это спланировать.",
    # ---- team.html ----
    "Meet Our": "Наша",
    "Team": "команда",
    "Simplifying Australian immigration since 2004 — with 2,000+ cases handled and a 99.8% success rate.": "Упрощаем австралийскую иммиграцию с 2004 года — более 2 000 дел и 99,8% успешных результатов.",
    "Principal Migration Agent": "Ведущий миграционный агент",
    "Founder of Visa2AU with over 20 years in Australian immigration law. Specialises in complex partner cases, refusals and ART appeals. NAATI-certified translator (Russian).": "Основатель Visa2AU с более чем 20-летним опытом в австралийском иммиграционном праве. Специализируется на сложных партнёрских делах, отказах и апелляциях в ART. Сертифицированный переводчик NAATI (русский).",
    "Registered Migration Agent": "Зарегистрированный миграционный агент",
    "Focuses on employer-sponsored programs (482/494/186), DAMA arrangements and skilled migration. Known for meticulous documentation and honest prospects assessments.": "Специализируется на программах спонсорства работодателем (482/494/186), соглашениях DAMA и квалифицированной миграции. Известен скрупулёзной подготовкой документов и честной оценкой перспектив.",
    "Client Coordination": "Координация клиентов",
    "Case management &amp; coordination": "Ведение и координация дел",
    "Coordinates casework from first instruction to lodgement, keeping clients, employers and authorities aligned at every step.": "Координирует работу по делу от первого поручения до подачи заявления, держа клиентов, работодателей и ведомства в курсе на каждом шаге.",
    "Administration Support, Client Coordination": "Административная поддержка, координация клиентов",
    "Multilingual support EN/RU": "Многоязычная поддержка EN/RU",
    "Keeps the office running and supports client coordination — organising consultations, assessments and document checklists, in English and Russian.": "Обеспечивает работу офиса и поддерживает координацию клиентов — организует консультации, оценки и чек-листы документов на английском и русском.",
    "Our Values": "Наши ценности",
    "Values &amp;": "Ценности и",
    "social responsibility": "социальная ответственность",
    "Integrity &amp; transparency": "Честность и прозрачность",
    "Honest, evidence-based advice. We never promise outcomes we cannot deliver — and you understand the realistic prospects of your case before proceeding.": "Честные советы, основанные на фактах. Мы никогда не обещаем результатов, которых не можем добиться, — и вы понимаете реальные перспективы вашего дела до начала работы.",
    "Social responsibility": "Социальная ответственность",
    "We believe in giving back. In select cases we undertake pro bono work for people in genuine need — including victims of domestic violence and those facing humanitarian crises.": "Мы верим в важность отдачи обществу. В отдельных случаях мы берём pro bono дела для людей, действительно нуждающихся в помощи, — включая жертв домашнего насилия и тех, кто столкнулся с гуманитарными кризисами.",
    "Client dedication": "Преданность клиентам",
    "Every case receives our full attention. Immigration decisions shape lives, families and futures — we treat yours with the seriousness and compassion it deserves.": "Каждое дело получает наше полное внимание. Иммиграционные решения меняют жизни, семьи и будущее — мы относимся к вашему делу с той серьёзностью и сочувствием, которых оно заслуживает.",
    "Continuous learning": "Постоянное обучение",
    "Immigration law changes frequently. Our agents maintain continuous professional development so our advice reflects the latest legislation, policy and case law.": "Иммиграционное право часто меняется. Наши агенты постоянно повышают квалификацию, чтобы наши рекомендации отражали актуальное законодательство, политику и прецедентную практику.",
    "Excellence in service": "Превосходство в сервисе",
    "Excellence in every aspect of our work — from document preparation to communication with the Department. Our goal: give every application its best possible chance.": "Превосходство в каждом аспекте нашей работы — от подготовки документов до взаимодействия с Департаментом. Наша цель: дать каждому заявлению наилучший шанс.",
    "Multicultural understanding": "Понимание разных культур",
    "Our team speaks English and Russian and works with clients from diverse backgrounds. We understand the challenges migrants face — and provide culturally sensitive service.": "Наша команда говорит на английском и русском и работает с клиентами из разных культур. Мы понимаем трудности мигрантов — и оказываем услуги с учётом культурных особенностей.",
    "About Visa2AU": "О Visa2AU",
    "Visa2AU Pty Ltd has guided individuals, families and employers through Australian immigration since 2004. From our North Sydney office we serve clients across Australia and worldwide — in English and Russian — with transparent fixed-fee pricing and a simple promise: honest advice about your prospects before you spend a dollar.": "Visa2AU Pty Ltd сопровождает частных лиц, семьи и работодателей в австралийской иммиграции с 2004 года. Из нашего офиса в North Sydney мы обслуживаем клиентов по всей Австралии и по всему миру — на английском и русском — с прозрачными фиксированными ценами и простым обещанием: честная оценка ваших перспектив до того, как вы потратите доллар.",
    "Natasha Arens, Principal Migration Agent at Visa2AU": "Natasha Arens, ведущий миграционный агент Visa2AU",
    "Denis, Client Coordination at Visa2AU": "Denis, координация клиентов в Visa2AU",
    "Franz, Administration Support, Client Coordination at Visa2AU": "Franz, административная поддержка и координация клиентов в Visa2AU",
}
