# -*- coding: utf-8 -*-
# Translation map B — French — pages: pricing.html, pay.html, donate.html
# Keys are exact substrings as they appear in the EN source (HTML entities preserved).
# Kept as-is (not translated): Visa2AU, visa2.au, MARN+numbers, subclass numbers,
# AUD, SBS, DAMA, SAF, Stripe, ABN, ANZSCO, CSOL, SSIT, TSS, SID, ENS, NAATI,
# Schedule 3, LMT, 4.55%, URLs, emails, phone numbers, addresses, symbols.

FR_TITLE = "Tarifs — honoraires fixes transparents | Visa2AU"
FR_DESC = "Tarifs transparents pour les services de visa australiens : consultations à 330 $/heure, visas partenaires à partir de 5 500 $ d'honoraires professionnels, parrainage par l'employeur à partir de 3 300 $. Honoraires fixes chiffrés avant tout engagement."

FR_TITLES = {
    "pricing.html": "Tarifs — honoraires fixes transparents | Visa2AU",
    "pay.html": "Payer une facture | Paiement sécurisé par carte | Visa2AU",
    "donate.html": "Soutenez notre action | Dons | Visa2AU",
}

FR_DESCS = {
    "pricing.html": "Tarifs transparents pour les services de visa australiens : consultations à 330 $/heure, visas partenaires à partir de 5 500 $ d'honoraires professionnels, parrainage par l'employeur à partir de 3 300 $. Honoraires fixes chiffrés avant tout engagement.",
    "pay.html": "Payez votre facture Visa2AU en toute sécurité par carte de crédit internationale. Frais transparents : les frais de traitement de carte de 4.55% sont détaillés avant le paiement.",
    "donate.html": "Le programme de responsabilité sociale de Visa2AU soutient l'éducation, les causes humanitaires et la préservation de la culture aborigène. Découvrez où vont vos dons — des contributions sécurisées via Stripe.",
}

FR_MAP = {
    # NOTE: dict order matters — longer/more specific keys MUST come before their
    # substrings (e.g. "Other Services" before "Service"). Apply keys in dict order.
    # ===== pricing.html =====
    "Other Services": "Autres services",
    "Invoice / Service Order Number *": "N° de facture / de bon de commande *",
    "Transparent <span class=\"text-gold-400\">Pricing</span>": "Tarifs <span class=\"text-gold-400\">transparents</span>",
    "No surprises. Fixed professional fees quoted before you commit, government charges itemised, and the card fee on /pay disclosed before you pay.": "Aucune surprise. Des honoraires professionnels fixes annoncés avant tout engagement, des frais gouvernementaux détaillés, et les frais de carte sur /pay indiqués avant le paiement.",
    "Online Consultation (1 hour)": "Consultation en ligne (1 heure)",
    "Professional visa assessment and advice — pro rata fees may apply": "Évaluation professionnelle du dossier et conseils — une facturation au prorata peut s'appliquer",
    "DAMA Consultation (1 hour)": "Consultation DAMA (1 heure)",
    "Designated Area Migration Agreement advice": "Conseils sur les accords Designated Area Migration Agreement",
    "Nil": "Gratuit",
    "Family &amp; Domestic Violence": "Violence familiale et domestique",
    "No fee for victims of domestic violence": "Aucun frais pour les victimes de violences domestiques",
    "Partner &amp; Family": "Partenaire & Famille",
    "Subclass": "Sous-classe",
    "Service": "Service",
    "Professional Fee": "Honoraires professionnels",
    "Government Charges": "Frais gouvernementaux",
    "Partner Visa (Onshore)": "Visa partenaire (onshore)",
    "$11,710 AUD (main) · $5,855 (secondary) · $2,930 (under 18)": "$11,710 AUD (principal) · $5,855 (conjoint) · $2,930 (moins de 18 ans)",
    "Partner Visa (Offshore)": "Visa partenaire (offshore)",
    "Prospective Marriage Visa": "Visa de mariage à venir",
    "NZ Citizen Family Relationship": "Relation familiale avec un citoyen néo-zélandais (NZ)",
    "Child Visa (Offshore)": "Visa enfant (offshore)",
    "Dependent Child (Temporary)": "Enfant à charge (temporaire)",
    "Combined temporary and permanent partner pathway. Schedule 3 may apply if not holding a substantive visa.": "Parcours combiné temporaire et permanent pour les visas partenaires. La Schedule 3 peut s'appliquer si vous ne détenez pas de visa substantif.",
    "Skilled Migration": "Migration qualifiée",
    "Skilled Independent Visa": "Visa indépendant qualifié",
    "Skilled Nominated Visa": "Visa qualifié avec nomination",
    "Skilled Regional (Permanent Residence)": "Visa régional qualifié (résidence permanente)",
    "Skilled Work Regional (Provisional)": "Visa régional de travail qualifié (provisoire)",
    "Employer-Sponsored": "Parrainés par l'employeur",
    "Skills in Demand — Employee": "Skills in Demand — Employé",
    "Skills in Demand — Employer SBS": "Skills in Demand — Employeur SBS",
    "Skills in Demand — Employer Nomination": "Skills in Demand — Nomination de l'employeur",
    "Itemised at engagement": "Détaillés à la signature du mandat",
    "Skilled Regional — Employee": "Skilled Regional — Employé",
    "Skilled Regional — Employer SBS": "Skilled Regional — Employeur SBS",
    "Skilled Regional — Employer Nomination": "Skilled Regional — Nomination de l'employeur",
    "Temporary Work (Short Stay Specialist)": "Travail temporaire (spécialiste de court séjour)",
    "Training Visa": "Visa de formation",
    "Temporary Activity Visa": "Visa d'activité temporaire",
    "Working Holiday Visa": "Visa vacances-travail",
    "Work and Holiday Visa": "Visa travail et vacances",
    "Government charges for employer-sponsored visas include sponsorship, nomination and SAF levy components — we itemise them fully in your engagement letter.": "Les frais gouvernementaux des visas parrainés par l'employeur incluent les composantes sponsorship, nomination et la taxe SAF — nous les détaillons intégralement dans votre lettre de mission.",
    "Visitor &amp; Short Stay": "Visiteur & court séjour",
    "Visitor — Tourist (offshore)": "Visiteur — Touriste (offshore)",
    "Visitor — Tourist (onshore)": "Visiteur — Touriste (onshore)",
    "Visitor — Sponsored Family": "Visiteur — Famille parrainée",
    "Visitor — Business Stream": "Visiteur — Volet affaires",
    "Visitor — Frequent Traveller (10-year)": "Visiteur — Voyageur fréquent (10 ans)",
    "Medical Treatment Visa": "Visa de traitement médical",
    "$0 (offshore) / $480 (in Australia)": "$0 (offshore) / $480 (en Australie)",
    "eVisitor Visa": "Visa eVisitor",
    "No charge": "Aucun frais",
    "Parent Visas": "Visas parentaux",
    "Parent Visa (Offshore)": "Visa parent (offshore)",
    "Contributory Parent Visa": "Visa parent contributif",
    "Staged contributory charges — quoted in strategy session": "Contributions échelonnées — chiffrées lors de la séance de stratégie",
    "Contributory Parent (Temporary)": "Visa parent contributif (temporaire)",
    "$31,930 AUD (first instalment)": "$31,930 AUD (premier versement)",
    "Contributory Aged Parent (Onshore)": "Visa parent âgé contributif (onshore)",
    "$4,835 AUD (first instalment)": "$4,835 AUD (premier versement)",
    "Sponsored Parent (Temporary)": "Visa parent parrainé (temporaire)",
    "870 (Combined)": "870 (combiné)",
    "Sponsored Parent (Visa + Sponsorship)": "Visa parent parrainé (visa + parrainage)",
    "$1,145 (visa) + $420 (sponsorship)": "$1,145 (visa) + $420 (parrainage)",
    "Parent strategy (queue vs contributory vs 870) should be mapped in a consultation before committing — the wrong choice is expensive.": "La stratégie parentale (file d'attente vs contributif vs 870) doit être définie lors d'une consultation avant tout engagement — un mauvais choix coûte cher.",
    "Other Services": "Autres services",
    "Student Visa": "Visa étudiant",
    "Protection Visa (Onshore)": "Visa de protection (onshore)",
    "Bridging Visa B — Travel Permission": "Visa relais B — autorisation de voyage",
    "Bridging Visa Application (other)": "Demande de visa relais (autre)",
    "Usually no charge": "Généralement sans frais",
    "Skills Assessment (Professional Occupation)": "Évaluation des compétences (profession qualifiée)",
    "$500–$1,200 AUD (authority fee)": "$500–$1,200 AUD (frais de l'organisme d'évaluation)",
    "Skills Assessment (Trade Occupation)": "Évaluation des compétences (métier technique)",
    "$300–$1,000 AUD (authority fee)": "$300–$1,000 AUD (frais de l'organisme d'évaluation)",
    "ART Tribunal Application (Visa Refusal Appeal)": "Recours au tribunal ART (appel de refus de visa)",
    "$3,496 AUD (50% refundable if successful)": "$3,496 AUD (50% remboursables en cas de succès)",
    "Citizenship by Conferral (general)": "Citoyenneté par attribution (général)",
    "Citizenship by Conferral (concession)": "Citoyenneté par attribution (concession)",
    "Citizenship by Descent": "Citoyenneté par descendance",
    "NAATI Certified Translation (per page)": "Traduction certifiée NAATI (par page)",
    "On demand": "Sur demande",
    "Document Authentication / Legalisation": "Authentification / légalisation de documents",
    "Government fees are set by the Department of Home Affairs and are subject to annual adjustment. Fees shown are current as of 1 July 2026. Additional charges may apply for health checks, police clearances, and biometrics. Professional fees are quoted and fixed in your engagement letter before work begins.": "Les frais gouvernementaux sont fixés par le ministère de l'Intérieur et peuvent être ajustés chaque année. Les frais indiqués sont en vigueur au 1er juillet 2026. Des frais supplémentaires peuvent s'appliquer pour les examens médicaux, les extraits de casier judiciaire et la biométrie. Les honoraires professionnels sont chiffrés et fixés dans votre lettre de mission avant le début du travail.",
    "Want an exact quote for your case?": "Vous voulez un devis exact pour votre dossier ?",
    "Book a consultation — you&#39;ll leave with a clear plan and a fixed fee in writing.": "Réservez une consultation — vous repartirez avec un plan clair et des honoraires fixes par écrit.",
    "Book a consultation →": "Réserver une consultation →",
    "Detailed Visa Assessment": "Évaluation détaillée du visa",
    # ===== pay.html =====
    "Pay an <span class=\"text-gold-400\">Invoice</span>": "Payer une <span class=\"text-gold-400\">facture</span>",
    "Secure card payment via Stripe. Enter your details exactly as they appear on your invoice or service order.": "Paiement sécurisé par carte via Stripe. Saisissez vos informations exactement comme elles figurent sur votre facture ou votre bon de commande.",
    "Full Name *": "Nom complet *",
    "Invoice / Service Order Number *": "N° de facture / de bon de commande *",
    "Invoice Amount (AUD) *": "Montant de la facture (AUD) *",
    "Payment summary": "Résumé du paiement",
    "Invoice amount": "Montant de la facture",
    "International card processing fee (4.55%)": "Frais de traitement de carte internationale (4.55%)",
    "Total charged to your card": "Total débité sur votre carte",
    "We are open about fees: when you choose to pay by international credit card, the Stripe processing cost (4.55%) is passed on to you — itemised here before you pay. To avoid the card fee, ask us for bank transfer details at <a href=\"mailto:info@visa2.au\" class=\"underline\">info@visa2.au</a>.": "Nous sommes transparents sur les frais : si vous choisissez de payer par carte de crédit internationale, le coût de traitement Stripe (4.55%) vous est refacturé — il est détaillé ici avant le paiement. Pour éviter ces frais de carte, demandez-nous les coordonnées bancaires pour un virement à <a href=\"mailto:info@visa2.au\" class=\"underline\">info@visa2.au</a>.",
    "Proceed to Secure Payment →": "Passer au paiement sécurisé →",
    "Stripe checkout in test mode — live keys are added at launch. Card details never touch our servers.": "Paiement Stripe en mode test — les clés de production seront ajoutées au lancement. Les données de carte ne touchent jamais nos serveurs.",
    "As shown on the invoice": "Tel qu'indiqué sur la facture",
    "e.g. V2AU-2026-041": "p. ex. V2AU-2026-041",
    # ===== donate.html =====
    "Our <span class=\"text-gold-400\">Commitment</span>": "Notre <span class=\"text-gold-400\">engagement</span>",
    "Smart immigration comes with social responsibility. Our giving program supports education, cultural preservation and humanitarian causes — in Australia and beyond.": "Une immigration intelligente va de pair avec la responsabilité sociale. Notre programme de dons soutient l'éducation, la préservation culturelle et les causes humanitaires — en Australie et au-delà.",
    "Visa2AU is committed to giving back": "Visa2AU s'engage à redonner à la communauté",
    "\nWe believe success comes with responsibility. Whether it's helping a child access education or preserving\n        Australia's rich Indigenous heritage, your support matters. Every contribution — big or small — helps build\n        a stronger, more connected community. Thank you for being part of our mission to create lasting positive change.\n": "\nNous croyons que le succès s'accompagne de responsabilité. Qu'il s'agisse d'aider un enfant à accéder à l'éducation ou de préserver\n        le riche héritage autochtone de l'Australie, votre soutien compte. Chaque contribution — grande ou petite — aide à construire\n        une communauté plus forte et plus unie. Merci de faire partie de notre mission de créer un changement positif durable.\n",
    "Where your donation <span class=\"text-gold-600 dark:text-gold-400\">goes</span>": "Où va votre <span class=\"text-gold-600 dark:text-gold-400\">don</span>",
    "We direct our efforts toward causes that create lasting, meaningful impact.": "Nous orientons nos efforts vers des causes qui créent un impact durable et significatif.",
    "Education support": "Soutien à l'éducation",
    "Education changes lives. Contributions help provide access to learning for underprivileged communities — scholarships, educational resources and skill-building programs.": "L'éducation change des vies. Les contributions aident à offrir l'accès à l'apprentissage aux communautés défavorisées — bourses, ressources pédagogiques et programmes de développement des compétences.",
    "Humanitarian causes": "Causes humanitaires",
    "We support organisations providing relief, protection and assistance to displaced individuals and families — standing with people rebuilding their lives in new communities.": "Nous soutenons des organisations qui apportent secours, protection et assistance aux personnes et familles déplacées — aux côtés de ceux qui reconstruisent leur vie dans de nouvelles communautés.",
    "Aboriginal cultural programs": "Programmes culturels aborigènes",
    "Australia&#39;s Indigenous heritage is deeply woven into its identity. We support programs that preserve Aboriginal culture, language and arts — honouring the world&#39;s oldest continuous culture.": "L'héritage autochtone de l'Australie est profondément tissé dans son identité. Nous soutenons des programmes qui préservent la culture, la langue et les arts aborigènes — honorant la plus ancienne culture continue du monde.",
    "Choose an amount (AUD)": "Choisissez un montant (AUD)",
    "Or a custom amount": "Ou un montant personnalisé",
    "Donate Securely →": "Faire un don sécurisé →",
    "Secure payment via Stripe (test mode until launch keys are added). Donations are not tax-deductible.": "Paiement sécurisé via Stripe (mode test jusqu'à l'ajout des clés de lancement). Les dons ne sont pas déductibles des impôts.",
    "Prefer to give with your visa services? Ask us to add a voluntary donation to your invoice.": "Vous préférez donner avec vos services de visa ? Demandez-nous d'ajouter un don volontaire à votre facture.",
}

FR_SKIPPED = [
    "Prices/amounts kept as-is: $330 AUD, $5,500 AUD, $2,200 AUD, $3,300 AUD, $700 AUD, $1,650 AUD, $3,960 AUD, $455 AUD, $6,135 AUD, $6,140 AUD, $630 AUD, $250 AUD, $1,195 AUD, $7,055 AUD, $4,400 AUD, $1,145 AUD, $2,500 AUD, $575 AUD, $1,100 AUD, $595 AUD, $85 AUD, $380 AUD, $25/$50/$100/$250, $0.00 / A$0.00",
    "Subclass cells kept: 820/801, 309/100, 300, 461, 101, 445, 189, 190, 191, 491, 482 (SID), 494, 400, 407, 408, 417, 462, 600, 602, 651, 103, 143, 173, 864, 870, 500, 866, BVB, BVA/B/C/E",
    "Symbols kept: \u2014 em-dash cells, \u2192 arrows",
    "JS-generated UI strings skipped (code, not markup): \"Opening secure checkout\u2026\", \"Checkout failed: \", \"unknown error\", \"Checkout failed \u2014 please try again or contact us.\", \"Proceed to Secure Payment \u2192\" (JS), \"Donate Securely \u2192\" / \"Donate A$\" (JS)",
    "Header/nav/footer/search-palette text outside <main id=\"main\"> skipped",
]
