# -*- coding: utf-8 -*-
# Translation map B — Russian — pages: pricing.html, pay.html, donate.html
# Keys are exact substrings as they appear in the EN source (HTML entities preserved).
# Kept as-is (not translated): Visa2AU, visa2.au, MARN+numbers, subclass numbers,
# AUD, SBS, DAMA, SAF, Stripe, ABN, ANZSCO, CSOL, SSIT, TSS, SID, ENS, NAATI,
# Schedule 3, LMT, 4.55%, URLs, emails, phone numbers, addresses, symbols.

RU_TITLE = "Цены — прозрачные фиксированные гонорары | Visa2AU"
RU_DESC = "Прозрачные цены на услуги по австралийским визам: консультации — $330/час, партнёрские визы — от $5,500 профессионального гонорара, спонсорство работодателя — от $3,300. Фиксированные гонорары называются до начала работы."

RU_TITLES = {
    "pricing.html": "Цены — прозрачные фиксированные гонорары | Visa2AU",
    "pay.html": "Оплатить счёт | Безопасная оплата картой | Visa2AU",
    "donate.html": "Поддержите нашу работу | Пожертвования | Visa2AU",
}

RU_DESCS = {
    "pricing.html": "Прозрачные цены на услуги по австралийским визам: консультации — $330/час, партнёрские визы — от $5,500 профессионального гонорара, спонсорство работодателя — от $3,300. Фиксированные гонорары называются до начала работы.",
    "pay.html": "Безопасно оплатите счёт Visa2AU международной кредитной картой. Прозрачные комиссии: комиссия за обработку карты 4.55% указывается до оплаты.",
    "donate.html": "Программа социальной ответственности Visa2AU поддерживает образование, гуманитарные инициативы и сохранение культуры аборигенов. Узнайте, куда идут ваши пожертвования, — безопасные взносы через Stripe.",
}

RU_MAP = {
    # NOTE: dict order matters — longer/more specific keys MUST come before their
    # substrings (e.g. "Other Services" before "Service"). Apply keys in dict order.
    # ===== pricing.html =====
    "Other Services": "Другие услуги",
    "Invoice / Service Order Number *": "Номер счёта / заказа на услуги *",
    "Transparent <span class=\"text-gold-400\">Pricing</span>": "Прозрачные <span class=\"text-gold-400\">цены</span>",
    "No surprises. Fixed professional fees quoted before you commit, government charges itemised, and the card fee on /pay disclosed before you pay.": "Никаких сюрпризов. Фиксированные профессиональные гонорары называются до начала работы, государственные сборы указаны отдельно, а комиссия за карту на /pay раскрывается до оплаты.",
    "Online Consultation (1 hour)": "Онлайн-консультация (1 час)",
    "Professional visa assessment and advice — pro rata fees may apply": "Профессиональная оценка визового дела и консультация — возможен пропорциональный расчёт",
    "DAMA Consultation (1 hour)": "Консультация по DAMA (1 час)",
    "Designated Area Migration Agreement advice": "Консультация по соглашению Designated Area Migration Agreement",
    "Nil": "Без оплаты",
    "Family &amp; Domestic Violence": "Семейное и домашнее насилие",
    "No fee for victims of domestic violence": "Без гонорара для жертв домашнего насилия",
    "Partner &amp; Family": "Партнёрские и семейные",
    "Subclass": "Подкласс",
    "Service": "Услуга",
    "Professional Fee": "Профессиональный гонорар",
    "Government Charges": "Государственные сборы",
    "Partner Visa (Onshore)": "Виза партнёра (оншор)",
    "$11,710 AUD (main) · $5,855 (secondary) · $2,930 (under 18)": "$11,710 AUD (основной) · $5,855 (второй) · $2,930 (до 18 лет)",
    "Partner Visa (Offshore)": "Виза партнёра (оффшор)",
    "Prospective Marriage Visa": "Виза для будущего брака",
    "NZ Citizen Family Relationship": "Семейные отношения с гражданином Новой Зеландии",
    "Child Visa (Offshore)": "Детская виза (оффшор)",
    "Dependent Child (Temporary)": "Зависимый ребёнок (временная)",
    "Combined temporary and permanent partner pathway. Schedule 3 may apply if not holding a substantive visa.": "Комбинированный путь временной и постоянной партнёрской визы. Schedule 3 может применяться, если у вас нет существенной визы.",
    "Skilled Migration": "Квалифицированная миграция",
    "Skilled Independent Visa": "Виза квалифицированного специалиста (независимая)",
    "Skilled Nominated Visa": "Виза квалифицированного специалиста (номинация)",
    "Skilled Regional (Permanent Residence)": "Квалифицированная региональная (постоянное резидентство)",
    "Skilled Work Regional (Provisional)": "Квалифицированная региональная рабочая (временная)",
    "Employer-Sponsored": "Спонсируемые работодателем",
    "Skills in Demand — Employee": "Skills in Demand — сотрудник",
    "Skills in Demand — Employer SBS": "Skills in Demand — работодатель SBS",
    "Skills in Demand — Employer Nomination": "Skills in Demand — номинация работодателя",
    "Itemised at engagement": "Детализируется при заключении договора",
    "Skilled Regional — Employee": "Skilled Regional — сотрудник",
    "Skilled Regional — Employer SBS": "Skilled Regional — работодатель SBS",
    "Skilled Regional — Employer Nomination": "Skilled Regional — номинация работодателя",
    "Temporary Work (Short Stay Specialist)": "Временная работа (краткосрочный специалист)",
    "Training Visa": "Учебная виза",
    "Temporary Activity Visa": "Временная виза для деятельности",
    "Working Holiday Visa": "Рабочая отпускная виза",
    "Work and Holiday Visa": "Виза «работа и отдых»",
    "Government charges for employer-sponsored visas include sponsorship, nomination and SAF levy components — we itemise them fully in your engagement letter.": "Государственные сборы по визам, спонсируемым работодателем, включают компоненты спонсорства, номинации и сбора SAF — мы полностью детализируем их в вашем договоре.",
    "Visitor &amp; Short Stay": "Гостевые и краткосрочные",
    "Visitor — Tourist (offshore)": "Гостевая — туристическая (оффшор)",
    "Visitor — Tourist (onshore)": "Гостевая — туристическая (оншор)",
    "Visitor — Sponsored Family": "Гостевая — спонсируемая семья",
    "Visitor — Business Stream": "Гостевая — деловой поток",
    "Visitor — Frequent Traveller (10-year)": "Гостевая — частый путешественник (10 лет)",
    "Medical Treatment Visa": "Виза для медицинского лечения",
    "$0 (offshore) / $480 (in Australia)": "$0 (оффшор) / $480 (в Австралии)",
    "eVisitor Visa": "Виза eVisitor",
    "No charge": "Без сбора",
    "Parent Visas": "Родительские визы",
    "Parent Visa (Offshore)": "Родительская виза (оффшор)",
    "Contributory Parent Visa": "Взносная родительская виза",
    "Staged contributory charges — quoted in strategy session": "Поэтапные взносные платежи — озвучиваются на стратегической сессии",
    "Contributory Parent (Temporary)": "Взносная родительская (временная)",
    "$31,930 AUD (first instalment)": "$31,930 AUD (первый взнос)",
    "Contributory Aged Parent (Onshore)": "Взносная родительская для пожилых (оншор)",
    "$4,835 AUD (first instalment)": "$4,835 AUD (первый взнос)",
    "Sponsored Parent (Temporary)": "Спонсируемая родительская (временная)",
    "870 (Combined)": "870 (комбинированная)",
    "Sponsored Parent (Visa + Sponsorship)": "Спонсируемая родительская (виза + спонсорство)",
    "$1,145 (visa) + $420 (sponsorship)": "$1,145 (виза) + $420 (спонсорство)",
    "Parent strategy (queue vs contributory vs 870) should be mapped in a consultation before committing — the wrong choice is expensive.": "Стратегию родительской визы (очередь vs взносная vs 870) следует определить на консультации до принятия решения — неверный выбор дорого обходится.",
    "Student Visa": "Студенческая виза",
    "Protection Visa (Onshore)": "Защитная виза (оншор)",
    "Bridging Visa B — Travel Permission": "Бриджинг-виза B — разрешение на поездку",
    "Bridging Visa Application (other)": "Заявление на бриджинг-визу (прочие)",
    "Usually no charge": "Обычно без сбора",
    "Skills Assessment (Professional Occupation)": "Оценка навыков (профессиональная профессия)",
    "$500–$1,200 AUD (authority fee)": "$500–$1,200 AUD (сбор оценивающего органа)",
    "Skills Assessment (Trade Occupation)": "Оценка навыков (рабочая профессия)",
    "$300–$1,000 AUD (authority fee)": "$300–$1,000 AUD (сбор оценивающего органа)",
    "ART Tribunal Application (Visa Refusal Appeal)": "Заявление в трибунал ART (апелляция по отказу в визе)",
    "$3,496 AUD (50% refundable if successful)": "$3,496 AUD (50% возвращается при успехе)",
    "Citizenship by Conferral (general)": "Гражданство по Conferral (общий)",
    "Citizenship by Conferral (concession)": "Гражданство по Conferral (льготный)",
    "Citizenship by Descent": "Гражданство по Descent",
    "NAATI Certified Translation (per page)": "NAATI-сертифицированный перевод (за страницу)",
    "On demand": "По запросу",
    "Document Authentication / Legalisation": "Аутентификация / легализация документов",
    "Government fees are set by the Department of Home Affairs and are subject to annual adjustment. Fees shown are current as of 1 July 2026. Additional charges may apply for health checks, police clearances, and biometrics. Professional fees are quoted and fixed in your engagement letter before work begins.": "Государственные сборы устанавливаются Департаментом внутренних дел и подлежат ежегодной корректировке. Указанные сборы актуальны на 1 июля 2026 года. Могут применяться дополнительные расходы на медосмотры, справки о несудимости и биометрию. Профессиональные гонорары фиксируются в договоре до начала работы.",
    "Want an exact quote for your case?": "Хотите точный расчёт для вашего дела?",
    "Book a consultation — you&#39;ll leave with a clear plan and a fixed fee in writing.": "Запишитесь на консультацию — вы уйдёте с чётким планом и фиксированным гонораром в письменном виде.",
    "Book a consultation →": "Записаться на консультацию →",
    "Detailed Visa Assessment": "Детальная оценка визы",
    # ===== pay.html =====
    "Pay an <span class=\"text-gold-400\">Invoice</span>": "Оплатите <span class=\"text-gold-400\">счёт</span>",
    "Secure card payment via Stripe. Enter your details exactly as they appear on your invoice or service order.": "Безопасная оплата картой через Stripe. Укажите данные точно так, как они указаны в вашем счёте или заказе на услуги.",
    "Full Name *": "Полное имя *",
    "Invoice Amount (AUD) *": "Сумма счёта (AUD) *",
    "Payment summary": "Сводка платежа",
    "Invoice amount": "Сумма счёта",
    "International card processing fee (4.55%)": "Комиссия за обработку международной карты (4.55%)",
    "Total charged to your card": "Итого к списанию с вашей карты",
    "We are open about fees: when you choose to pay by international credit card, the Stripe processing cost (4.55%) is passed on to you — itemised here before you pay. To avoid the card fee, ask us for bank transfer details at <a href=\"mailto:info@visa2.au\" class=\"underline\">info@visa2.au</a>.": "Мы открыто говорим о комиссиях: при оплате международной кредитной картой стоимость обработки Stripe (4.55%) перекладывается на вас — она указана здесь до оплаты. Чтобы избежать комиссии за карту, запросите реквизиты банковского перевода по адресу <a href=\"mailto:info@visa2.au\" class=\"underline\">info@visa2.au</a>.",
    "Proceed to Secure Payment →": "Перейти к безопасной оплате →",
    "Stripe checkout in test mode — live keys are added at launch. Card details never touch our servers.": "Оплата Stripe в тестовом режиме — рабочие ключи будут добавлены при запуске. Данные карты никогда не попадают на наши серверы.",
    "As shown on the invoice": "Как указано в счёте",
    "e.g. V2AU-2026-041": "напр., V2AU-2026-041",
    # ===== donate.html =====
    "Our <span class=\"text-gold-400\">Commitment</span>": "Наша <span class=\"text-gold-400\">приверженность</span>",
    "Smart immigration comes with social responsibility. Our giving program supports education, cultural preservation and humanitarian causes — in Australia and beyond.": "Разумная иммиграция идёт рука об руку с социальной ответственностью. Наша программа пожертвований поддерживает образование, сохранение культуры и гуманитарные инициативы — в Австралии и за её пределами.",
    "Visa2AU is committed to giving back": "Visa2AU привержен идее отдавать обществу",
    "\nWe believe success comes with responsibility. Whether it's helping a child access education or preserving\n        Australia's rich Indigenous heritage, your support matters. Every contribution — big or small — helps build\n        a stronger, more connected community. Thank you for being part of our mission to create lasting positive change.\n": "\nМы верим, что успех идёт вместе с ответственностью. Помогаем ли мы ребёнку получить образование или сохраняем\n        богатое наследие коренных народов Австралии — ваша поддержка важна. Каждое пожертвование — большое или малое — помогает строить\n        более сильное и сплочённое сообщество. Спасибо, что вы с нами в нашей миссии создавать устойчивые позитивные изменения.\n",
    "Where your donation <span class=\"text-gold-600 dark:text-gold-400\">goes</span>": "Куда идут ваши <span class=\"text-gold-600 dark:text-gold-400\">пожертвования</span>",
    "We direct our efforts toward causes that create lasting, meaningful impact.": "Мы направляем усилия на инициативы, создающие устойчивый и значимый эффект.",
    "Education support": "Поддержка образования",
    "Education changes lives. Contributions help provide access to learning for underprivileged communities — scholarships, educational resources and skill-building programs.": "Образование меняет жизни. Пожертвования помогают обеспечить доступ к обучению для малообеспеченных сообществ — стипендии, учебные ресурсы и программы развития навыков.",
    "Humanitarian causes": "Гуманитарные инициативы",
    "We support organisations providing relief, protection and assistance to displaced individuals and families — standing with people rebuilding their lives in new communities.": "Мы поддерживаем организации, оказывающие помощь, защиту и поддержку перемещённым лицам и семьям — мы рядом с людьми, заново строящими свою жизнь в новых сообществах.",
    "Aboriginal cultural programs": "Программы сохранения культуры аборигенов",
    "Australia&#39;s Indigenous heritage is deeply woven into its identity. We support programs that preserve Aboriginal culture, language and arts — honouring the world&#39;s oldest continuous culture.": "Наследие коренных народов Австралии глубоко вплетено в её идентичность. Мы поддерживаем программы, сохраняющие культуру, язык и искусство аборигенов, — отдавая дань старейшей непрерывной культуре в мире.",
    "Choose an amount (AUD)": "Выберите сумму (AUD)",
    "Or a custom amount": "Или свою сумму",
    "Donate Securely →": "Пожертвовать безопасно →",
    "Secure payment via Stripe (test mode until launch keys are added). Donations are not tax-deductible.": "Безопасный платёж через Stripe (тестовый режим до добавления ключей запуска). Пожертвования не подлежат налоговому вычету.",
    "Prefer to give with your visa services? Ask us to add a voluntary donation to your invoice.": "Хотите поддержать нас вместе с визовыми услугами? Попросите добавить добровольное пожертвование в ваш счёт.",
}

RU_SKIPPED = [
    "Prices/amounts kept as-is: $330 AUD, $5,500 AUD, $2,200 AUD, $3,300 AUD, $700 AUD, $1,650 AUD, $3,960 AUD, $455 AUD, $6,135 AUD, $6,140 AUD, $630 AUD, $250 AUD, $1,195 AUD, $7,055 AUD, $4,400 AUD, $1,145 AUD, $2,500 AUD, $575 AUD, $1,100 AUD, $595 AUD, $85 AUD, $380 AUD, $25/$50/$100/$250, $0.00 / A$0.00",
    "Subclass cells kept: 820/801, 309/100, 300, 461, 101, 445, 189, 190, 191, 491, 482 (SID), 494, 400, 407, 408, 417, 462, 600, 602, 651, 103, 143, 173, 864, 870, 500, 866, BVB, BVA/B/C/E",
    "Symbols kept: \u2014 em-dash cells, \u2192 arrows",
    "JS-generated UI strings skipped (code, not markup): \"Opening secure checkout\u2026\", \"Checkout failed: \", \"unknown error\", \"Checkout failed \u2014 please try again or contact us.\", \"Proceed to Secure Payment \u2192\" (JS), \"Donate Securely \u2192\" / \"Donate A$\" (JS)",
    "Header/nav/footer/search-palette text outside <main id=\"main\"> skipped",
]
