# -*- coding: utf-8 -*-
# FR translation map for app/employers.html + app/privacy.html
# Keys are EXACT substrings of the source files (HTML entities preserved).

FR_TITLE = "Espace employeurs — Parrainez des travailleurs qualifiés | Visa2AU"
FR_DESC = "Pourquoi les entreprises australiennes parrainent des migrants qualifiés : 482 Skills in Demand, 494 régional avec concessions DAMA et 186 nomination permanente. Seuils salariaux, listes de métiers, régions DAMA et conformité — expliqués par des agents enregistrés MARN."

FR_MAP = {
    # ---- employers.html ----
    "Employer <span class=\"text-gold-400\">Hub</span>": "Espace <span class=\"text-gold-400\">employeurs</span>",
    "Can't find the skills locally? Sponsorship is a system, not a gamble — and right now it is one of the strongest hiring tools Australian businesses have. We run it end to end: SBS, nomination, LMT, visa and compliance.": "Vous ne trouvez pas les compétences localement ? Le parrainage est un système, pas un pari — et c'est aujourd'hui l'un des outils de recrutement les plus puissants dont disposent les entreprises australiennes. Nous le gérons de A à Z : SBS, nomination, LMT, visa et conformité.",
    "Discuss Your Hiring Needs →": "Discuter de vos besoins de recrutement →",
    "The Opportunity": "L'opportunité",
    "Why smart businesses sponsor<span class=\"text-gold-500\"> skilled migrants</span>": "Pourquoi les entreprises avisées parrainent<span class=\"text-gold-500\"> des travailleurs qualifiés</span>",
    "Australia's migration program is built around a simple truth: the economy has skill gaps that local hiring alone cannot fill. Sponsorship is how a business turns that national gap into its own competitive advantage.": "Le programme de migration australien repose sur une vérité simple : l'économie présente des pénuries de compétences que le seul recrutement local ne peut pas combler. Le parrainage est le moyen pour une entreprise de transformer ce déficit national en avantage concurrentiel.",
    "A business case, not a favour": "Un argument commercial, pas une faveur",
    "When a role sits vacant for months, the cost of not sponsoring — lost contracts, overtime, stalled growth — usually exceeds the cost of sponsorship many times over. Sponsorship turns an urgent vacancy into a long-term team member.": "Lorsqu'un poste reste vacant pendant des mois, le coût de ne pas parrainer — contrats perdus, heures supplémentaires, croissance à l'arrêt — dépasse généralement de plusieurs fois le coût du parrainage. Le parrainage transforme une vacance urgente en membre d'équipe à long terme.",
    "Good for the economy you operate in": "Bénéfique pour l'économie dans laquelle vous opérez",
    "Skilled migrants fill verified shortages, pay taxes, spend locally and train Australian colleagues. Regional sponsorship in particular keeps essential services — from kitchens to clinics — running where locals are hardest to find.": "Les migrants qualifiés comblent des pénuries vérifiées, paient des impôts, dépensent localement et forment leurs collègues australiens. Le parrainage régional maintient notamment des services essentiels — des cuisines aux cliniques — là où il est le plus difficile de trouver de la main-d'œuvre locale.",
    "Government actively supports it": "Le gouvernement soutient activement cette démarche",
    "The program is designed for employers: dedicated sponsored streams, priority processing in regional areas, occupation lists covering hundreds of roles, and DAMA concessions where standard settings don&#39;t fit. The framework exists to be used — compliantly.": "Le programme est conçu pour les employeurs : volets de parrainage dédiés, traitement prioritaire dans les régions, listes de métiers couvrant des centaines de postes et concessions DAMA lorsque les conditions standard ne conviennent pas. Ce cadre est fait pour être utilisé — en toute conformité.",
    "A retention advantage competitors miss": "Un avantage de rétention que vos concurrents négligent",
    "A sponsored employee working toward permanent residency is one of the most loyal hires you will make. The 482 → 186 pathway is a structured, multi-year retention plan backed by migration law.": "Un employé parrainé qui vise la résidence permanente est l'un des recrutements les plus loyaux que vous ferez. La voie 482 → 186 est un plan de rétention structuré sur plusieurs années, adossé au droit de la migration.",
    "Sponsorship Programs": "Programmes de parrainage",
    "Three pathways to the<span class=\"text-gold-500\"> skills you need</span>": "Trois voies vers<span class=\"text-gold-500\"> les compétences dont vous avez besoin</span>",
    "Skills in Demand (SID)": "Compétences en demande (SID)",
    "Subclass 482": "Sous-classe 482",
    "Standard Business Sponsorship (SBS) setup": "Mise en place du parrainage d'entreprise standard (SBS)",
    "Labour market testing evidence": "Preuves du test du marché du travail (LMT)",
    "CSOL occupations — most skilled roles covered": "Métiers CSOL — la plupart des postes qualifiés couverts",
    "Clear 186 PR pathway for your employee": "Voie claire vers la résidence permanente (186) pour votre employé",
    "Full details →": "Tous les détails →",
    "Skilled Employer Sponsored Regional": "Parrainage régional des travailleurs qualifiés",
    "Subclass 494": "Sous-classe 494",
    "For regional employers": "Pour les employeurs régionaux",
    "DAMA concessions: age, English, salary, occupation lists": "Concessions DAMA : âge, anglais, salaire, listes de métiers",
    "5-year visa with 191 PR pathway": "Visa de 5 ans avec voie vers la résidence permanente (191)",
    "We handle DAMA endorsement end to end": "Nous gérons l'endossement DAMA de A à Z",
    "Employer Nomination Scheme": "Schéma de nomination de l'employeur",
    "Subclass 186": "Sous-classe 186",
    "Permanent residency for key staff": "Résidence permanente pour les employés clés",
    "Direct Entry or 482 transition": "Entrée directe ou transition depuis le 482",
    "Retention tool your competitors may not offer": "Un outil de rétention que vos concurrents n'offrent peut-être pas",
    "Genuine-position documentation handled": "Documentation du poste authentique prise en charge",
    "The Ground Rules": "Les règles de base",
    "Occupation lists and salary floors,<span class=\"text-gold-500\"> in plain English</span>": "Listes de métiers et seuils salariaux,<span class=\"text-gold-500\"> en langage clair</span>",
    "Two gates decide every sponsorship: <strong class=\"text-navy-800 dark:text-white\">is the occupation eligible?</strong> and <strong class=\"text-navy-800 dark:text-white\">does the salary meet the floor?</strong> Here are the current settings — we confirm your specific role before you spend anything.": "Deux conditions décident de chaque parrainage : <strong class=\"text-navy-800 dark:text-white\">le métier est-il éligible ?</strong> et <strong class=\"text-navy-800 dark:text-white\">le salaire atteint-il le seuil ?</strong> Voici les paramètres actuels — nous confirmons votre rôle précis avant que vous ne dépensiez quoi que ce soit.",
    "Core Skills income threshold": "Seuil de revenu Core Skills",
    "Minimum salary for the 482 Core Skills stream — the higher of this or the market salary rate applies.": "Salaire minimum pour le volet 482 Core Skills — le plus élevé entre ce montant et le taux de salaire du marché s'applique.",
    "Specialist Skills threshold (SSIT)": "Seuil Specialist Skills (SSIT)",
    "From 1 July 2026. Opens the fast-tracked Specialist stream with no occupation list requirement.": "À partir du 1er juillet 2026. Ouvre le volet Specialist à traitement rapide, sans exigence de liste de métiers.",
    "Core Skills Occupation List": "Liste des métiers Core Skills",
    "Hundreds of skilled occupations eligible for sponsorship — most professional and trade roles are covered.": "Des centaines de métiers qualifiés éligibles au parrainage — la plupart des postes professionnels et techniques sont couverts.",
    "ANZSCO eligibility (Specialist)": "Éligibilité ANZSCO (Specialist)",
    "Levels 1–2, 4–6": "Niveaux 1–2, 4–6",
    "Specialist stream excludes trades workers, machinery operators and labourers — but needs no list.": "Le volet Specialist exclut les ouvriers qualifiés, les opérateurs de machines et les manœuvres — mais ne requiert aucune liste.",
    "DAMA — Designated Area Migration Agreements": "DAMA — accords de migration pour zones désignées",
    "When standard settings don't fit, regional Australia opens a second door.": "Lorsque les conditions standard ne conviennent pas, l'Australie régionale ouvre une seconde porte.",
    "A DAMA is a formal agreement between the Australian Government and a regional authority. It lets endorsed\n          local employers sponsor workers with <strong class=\"text-white\">concessions standard programs don't offer</strong> —\n          broader occupation lists, lower English and salary thresholds, age concessions — in exchange for committing\n          to the region. For regional businesses, it is often the difference between a filled role and a closed door.": "Un DAMA est un accord formel entre le gouvernement australien et une autorité régionale. Il permet aux\n          employeurs locaux agréés de parrainer des travailleurs avec des <strong class=\"text-white\">concessions que les programmes standard n'offrent pas</strong> —\n          listes de métiers élargies, seuils d'anglais et de salaire abaissés, concessions sur l'âge — en échange d'un engagement\n          envers la région. Pour les entreprises régionales, c'est souvent la différence entre un poste pourvu et une porte fermée.",
    "Where DAMA wins": "Où DAMA l'emporte",
    "Occupations not on standard lists become sponsorable": "Les métiers absents des listes standard deviennent parrainables",
    "Concessions on English, salary, age and skills where justified": "Concessions sur l'anglais, le salaire, l'âge et les compétences lorsque justifié",
    "Permanent residency pathways (via 494 → 191 or 186) that attract committed staff": "Voies vers la résidence permanente (via 494 → 191 ou 186) qui attirent des employés engagés",
    "Designed exactly for employers who cannot fill roles locally": "Conçu précisément pour les employeurs qui ne peuvent pas pourvoir de postes localement",
    "What to weigh honestly": "Ce qu'il faut peser honnêtement",
    "Two-stage process: regional endorsement first, then the labour agreement — allow months, not weeks": "Processus en deux étapes : d'abord l'endossement régional, puis l'accord de main-d'œuvre — prévoyez des mois, pas des semaines",
    "Annual nomination caps negotiated per agreement": "Plafonds annuels de nominations négociés par accord",
    "Employee must genuinely live and work in the designated region": "L'employé doit réellement vivre et travailler dans la région désignée",
    "Full sponsorship obligations and compliance monitoring still apply": "Les obligations complètes de parrainage et le suivi de conformité restent applicables",
    "Active DAMA regions": "Régions DAMA actives",
    "Each agreement has its own occupation list and concession settings — we confirm current terms with the regional authority before advising you.": "Chaque accord a sa propre liste de métiers et ses concessions — nous confirmons les conditions en vigueur auprès de l'autorité régionale avant de vous conseiller.",
    "Active": "Active",
    "Concessions:": "Concessions :",
    "Reduced English, lower skills thresholds, broader occupation list, salary concessions for some occupations": "Anglais réduit, seuils de compétences abaissés, liste de métiers élargie, concessions salariales pour certains métiers",
    "Two DAMAs covering Adelaide and all of regional South Australia — 1,000+ endorsed employers.": "Deux DAMA couvrant Adélaïde et toute l'Australie-Méridionale régionale — plus de 1 000 employeurs agréés.",
    "Lower English for some occupations, age concessions up to 50, skills concessions, broader occupation list": "Anglais abaissé pour certains métiers, concessions d'âge jusqu'à 50 ans, concessions de compétences, liste de métiers élargie",
    "One DAMA covering the entire NT — all NT employers can access it.": "Un seul DAMA couvrant tout le Territoire du Nord — tous les employeurs du NT peuvent y accéder.",
    "English and skills concessions for selected occupations, PR pathways available": "Concessions d'anglais et de compétences pour certains métiers, voies de résidence permanente disponibles",
    "Central and western NSW — Dubbo, Wagga and surrounding areas.": "Centre et ouest de la Nouvelle-Galles du Sud — Dubbo, Wagga et les environs.",
    "English, skills and experience concessions for selected occupations": "Concessions d'anglais, de compétences et d'expérience pour certains métiers",
    "Cairns and FNQ — strong support for tourism and hospitality.": "Cairns et le FNQ — un fort soutien au tourisme et à l'hôtellerie-restauration.",
    "Skills and English concessions for mining-related occupations": "Concessions de compétences et d'anglais pour les métiers liés aux mines",
    "Kalgoorlie region — resources sector workforce.": "Région de Kalgoorlie — main-d'œuvre du secteur des ressources.",
    "Lower thresholds for dairy, agriculture and manufacturing occupations": "Seuils abaissés pour les métiers de la laiterie, de l'agriculture et de la fabrication",
    "Regional Victoria — farming and agricultural sectors.": "Victoria régionale — secteurs agricoles.",
    "Broader occupation list incl. trades and hospitality, English and skills concessions": "Liste de métiers élargie incluant les métiers techniques et l'hôtellerie-restauration, concessions d'anglais et de compétences",
    "Bunbury and Margaret River region.": "Région de Bunbury et de Margaret River.",
    "Skills and experience concessions for mining and resources occupations": "Concessions de compétences et d'expérience pour les métiers des mines et des ressources",
    "FIFO and residential workforce needs.": "Besoins en main-d'œuvre FIFO et résidente.",
    "Lower English, broader occupation list incl. tourism and hospitality": "Anglais abaissé, liste de métiers élargie incluant le tourisme et l'hôtellerie-restauration",
    "Tourism and remote community services.": "Tourisme et services aux communautés éloignées.",
    "Similar concessions with tourism and hospitality focus": "Concessions similaires axées sur le tourisme et l'hôtellerie-restauration",
    "Broome and surrounding areas.": "Broome et ses environs.",
    "Not sure if your region qualifies?": "Vous ne savez pas si votre région est éligible ?",
    "DAMA consultation (1 hour, $330 AUD) — we map your role, region and concessions, and tell you plainly whether DAMA is worth pursuing.": "Consultation DAMA (1 heure, 330 $ AUD) — nous analysons votre poste, votre région et les concessions, et vous disons clairement si DAMA vaut la peine.",
    "Book a DAMA consultation": "Réserver une consultation DAMA",
    "Compliance, handled": "Conformité, prise en charge",
    "Sponsorship obligations are real — and manageable.": "Les obligations de parrainage sont réelles — et gérables.",
    "Sponsors take on legal obligations for the life of the sponsorship. None of them are difficult with the right\n          settings from day one — we build compliance into the application, not after it.": "Les parrains assument des obligations légales pour toute la durée du parrainage. Aucune n'est difficile avec les bons\n          réglages dès le premier jour — nous intégrons la conformité dans la demande, pas après.",
    "Pay at least the market salary rate and the relevant income threshold": "Payer au moins le taux de salaire du marché et le seuil de revenu applicable",
    "Pay the Skilling Australians Fund (SAF) levy for each nomination": "Payer la contribution au Skilling Australians Fund (SAF) pour chaque nomination",
    "Ensure the worker works only in the nominated occupation": "Veiller à ce que le travailleur n'exerce que le métier nommé",
    "Notify the Department of prescribed changes (role, location, business structure)": "Notifier au Département les changements prescrits (poste, lieu, structure de l'entreprise)",
    "Cooperate with monitoring — records must be audit-ready": "Coopérer au suivi — les registres doivent être prêts pour un audit",
    "Never recover sponsorship or nomination costs from the visa holder": "Ne jamais récupérer les coûts de parrainage ou de nomination auprès du titulaire du visa",
    "How It Works": "Comment ça marche",
    "From vacancy to visa grant in<span class=\"text-gold-500\"> four steps</span>": "De la vacance à l'octroi du visa en<span class=\"text-gold-500\"> quatre étapes</span>",
    "Feasibility": "Faisabilité",
    "We confirm your eligibility to sponsor, the right program, and honest costs — before you commit.": "Nous confirmons votre éligibilité au parrainage, le bon programme et des coûts transparents — avant que vous ne vous engagiez.",
    "Sponsorship": "Parrainage",
    "SBS or labour agreement application prepared and lodged, with compliance settings from day one.": "Demande de SBS ou d'accord de main-d'œuvre préparée et déposée, avec des réglages de conformité dès le premier jour.",
    "Nomination &amp; Visa": "Nomination et visa",
    "Position, salary (AMSR/threshold), LMT and the employee&#39;s visa — managed as one project.": "Poste, salaire (AMSR/seuil), LMT et visa de l'employé — gérés comme un seul projet.",
    "Compliance &amp; PR": "Conformité et résidence permanente",
    "Sponsorship obligations, monitoring, and the PR pathway (186/191) planned from the start.": "Obligations de parrainage, suivi et voie vers la résidence permanente (186/191) planifiés dès le départ.",
    "Ready to sponsor skilled workers?": "Prêt à parrainer des travailleurs qualifiés ?",
    "Book an employer consultation — we&#39;ll assess your eligibility, the right program, and give you a fixed-fee quote. Consultations $330 AUD per hour.": "Réservez une consultation employeur — nous évaluerons votre éligibilité, le bon programme et vous remettrons un devis à prix fixe. Consultations : 330 $ AUD de l'heure.",
    "Book a consultation →": "Réserver une consultation →",
    "Detailed Visa Assessment": "Évaluation de visa détaillée",
    # ---- privacy.html ----
    "Privacy Policy &amp; Terms | Visa2AU": "Politique de confidentialité &amp; conditions | Visa2AU",
    "How Visa2AU collects, uses and protects your personal information, and the terms of using this website.": "Comment Visa2AU collecte, utilise et protège vos informations personnelles, et les conditions d'utilisation de ce site web.",
    "Privacy Policy & <span class=\"text-gold-400\">Terms</span>": "Politique de confidentialité et <span class=\"text-gold-400\">conditions</span>",
    "Privacy Policy": "Politique de confidentialité",
    "Visa2AU Pty Ltd (ABN 36676512397) handles personal information in accordance with the Privacy Act 1988 (Cth) and the Australian Privacy Principles (APPs).": "Visa2AU Pty Ltd (ABN 36676512397) traite les informations personnelles conformément au Privacy Act 1988 (Cth) et aux principes australiens de confidentialité (APPs).",
    "What we collect": "Ce que nous collectons",
    "Contact details you submit via forms (name, email, phone, message).": "Coordonnées que vous soumettez via les formulaires (nom, e-mail, téléphone, message).",
    "Payment identifiers when you pay an invoice (processed by Stripe — card details never touch our servers).": "Identifiants de paiement lorsque vous payez une facture (traités par Stripe — les données de carte ne touchent jamais nos serveurs).",
    "Video consultation metadata (hosted by Daily.co; consultations are recorded for quality and compliance with your consent shown before joining).": "Métadonnées des consultations vidéo (hébergées par Daily.co ; les consultations sont enregistrées à des fins de qualité et de conformité avec votre consentement affiché avant de rejoindre).",
    "Voice assistant interactions (processed by ElevenLabs, where enabled) used to respond to your enquiry.": "Interactions avec l'assistant vocal (traitées par ElevenLabs, lorsqu'il est activé) utilisées pour répondre à votre demande.",
    "How we use it": "Comment nous les utilisons",
    "To respond to enquiries, provide migration services, meet our professional obligations, and improve this website. We do not sell personal information.": "Pour répondre aux demandes, fournir des services de migration, honorer nos obligations professionnelles et améliorer ce site web. Nous ne vendons pas d'informations personnelles.",
    "Cross-border disclosure": "Divulgation transfrontalière",
    "Some service providers (Stripe, Daily.co, ElevenLabs, Cloudflare) process data overseas. We take reasonable steps to ensure they handle it consistently with the APPs (APP 8).": "Certains fournisseurs de services (Stripe, Daily.co, ElevenLabs, Cloudflare) traitent des données à l'étranger. Nous prenons des mesures raisonnables pour qu'ils les traitent conformément aux APPs (APP 8).",
    "Access and correction": "Accès et correction",
    "You may request access to, or correction of, your personal information at any time via": "Vous pouvez demander l'accès à vos informations personnelles ou leur correction à tout moment via",
    "Terms of Use": "Conditions d'utilisation",
    "Information, not advice": "Information, pas conseil",
    "Content on this website — including visa guides, the Pathway Finder, search results and the voice assistant — is general information only. It is not migration advice, cannot replace a consultation with a registered migration agent, and may not reflect the latest legislative changes. Individual advice is provided only under a written engagement.": "Le contenu de ce site web — y compris les guides de visa, le Pathway Finder, les résultats de recherche et l'assistant vocal — est fourni à titre d'information générale uniquement. Il ne constitue pas un conseil en migration, ne remplace pas une consultation avec un agent de migration enregistré et peut ne pas refléter les dernières évolutions législatives. Des conseils individuels ne sont fournis que dans le cadre d'un engagement écrit.",
    "Registrations": "Enregistrements",
    "Migration advice is provided by registered migration agents: MARN 0534230 (N. Arens), 2418663 (S. Vinnichenko), operating under the Migration Agents Code of Conduct (mara.gov.au).": "Les conseils en migration sont fournis par des agents de migration enregistrés : MARN 0534230 (N. Arens), 2418663 (S. Vinnichenko), exerçant conformément au Migration Agents Code of Conduct (mara.gov.au).",
    "Historical results": "Résultats historiques",
    "Success-rate figures describe our historical record and do not guarantee the outcome of any future application.": "Les taux de réussite décrivent notre bilan historique et ne garantissent pas l'issue d'une future demande.",
    "Contact": "Contact",
}
