# -*- coding: utf-8 -*-
# RU translation map for app/employers.html + app/privacy.html
# Keys are EXACT substrings of the source files (HTML entities preserved).

RU_TITLE = "Работодателям — спонсируйте квалифицированных специалистов | Visa2AU"
RU_DESC = "Почему австралийские компании спонсируют квалифицированных мигрантов: 482 Skills in Demand, 494 региональная с уступками DAMA и 186 постоянная номинация. Зарплатные пороги, списки профессий, регионы DAMA и соответствие требованиям — объясняют агенты, зарегистрированные в MARN."

RU_MAP = {
    # ---- employers.html ----
    "Employer <span class=\"text-gold-400\">Hub</span>": "Центр для <span class=\"text-gold-400\">работодателей</span>",
    "Can't find the skills locally? Sponsorship is a system, not a gamble — and right now it is one of the strongest hiring tools Australian businesses have. We run it end to end: SBS, nomination, LMT, visa and compliance.": "Не можете найти нужных специалистов на месте? Спонсорство — это система, а не лотерея, и сейчас это один из самых сильных инструментов найма для австралийских компаний. Мы ведём его под ключ: SBS, номинация, LMT, виза и соответствие требованиям.",
    "Discuss Your Hiring Needs →": "Обсудить ваши потребности в найме →",
    "The Opportunity": "Возможность",
    "Why smart businesses sponsor<span class=\"text-gold-500\"> skilled migrants</span>": "Почему дальновидные компании спонсируют<span class=\"text-gold-500\"> квалифицированных мигрантов</span>",
    "Australia's migration program is built around a simple truth: the economy has skill gaps that local hiring alone cannot fill. Sponsorship is how a business turns that national gap into its own competitive advantage.": "Миграционная программа Австралии строится на простой истине: в экономике есть дефицит навыков, который один лишь местный найм закрыть не может. Спонсорство — это способ превратить национальный дефицит в собственное конкурентное преимущество.",
    "A business case, not a favour": "Бизнес-обоснование, а не одолжение",
    "When a role sits vacant for months, the cost of not sponsoring — lost contracts, overtime, stalled growth — usually exceeds the cost of sponsorship many times over. Sponsorship turns an urgent vacancy into a long-term team member.": "Когда должность пустует месяцами, цена отказа от спонсорства — потерянные контракты, сверхурочные, остановка роста — обычно во много раз превышает стоимость спонсорства. Спонсорство превращает срочную вакансию в долгосрочного члена команды.",
    "Good for the economy you operate in": "Выгодно для экономики, в которой вы работаете",
    "Skilled migrants fill verified shortages, pay taxes, spend locally and train Australian colleagues. Regional sponsorship in particular keeps essential services — from kitchens to clinics — running where locals are hardest to find.": "Квалифицированные мигранты закрывают подтверждённый дефицит, платят налоги, тратят деньги на месте и обучают австралийских коллег. Особенно региональное спонсорство позволяет держать на плаву ключевые службы — от кухонь до клиник — там, где местных работников найти труднее всего.",
    "Government actively supports it": "Правительство активно это поддерживает",
    "The program is designed for employers: dedicated sponsored streams, priority processing in regional areas, occupation lists covering hundreds of roles, and DAMA concessions where standard settings don&#39;t fit. The framework exists to be used — compliantly.": "Программа создана для работодателей: отдельные спонсорские потоки, приоритетное рассмотрение в региональных районах, списки профессий на сотни ролей и уступки DAMA там, где стандартные условия не подходят. Эта система создана, чтобы ей пользовались — с соблюдением требований.",
    "A retention advantage competitors miss": "Преимущество в удержании сотрудников, которое упускают конкуренты",
    "A sponsored employee working toward permanent residency is one of the most loyal hires you will make. The 482 → 186 pathway is a structured, multi-year retention plan backed by migration law.": "Спонсируемый сотрудник, идущий к постоянному резидентству, — один из самых лояльных, кого вы наймёте. Путь 482 → 186 — это структурированный многолетний план удержания, подкреплённый миграционным законодательством.",
    "Sponsorship Programs": "Программы спонсорства",
    "Three pathways to the<span class=\"text-gold-500\"> skills you need</span>": "Три пути к<span class=\"text-gold-500\"> нужным вам навыкам</span>",
    "Skills in Demand (SID)": "Востребованные навыки (SID)",
    "Subclass 482": "Подкласс 482",
    "Standard Business Sponsorship (SBS) setup": "Оформление стандартного спонсорства бизнеса (SBS)",
    "Labour market testing evidence": "Доказательства проверки рынка труда (LMT)",
    "CSOL occupations — most skilled roles covered": "Профессии CSOL — покрыто большинство квалифицированных ролей",
    "Clear 186 PR pathway for your employee": "Понятный путь к постоянному резидентству (186) для вашего сотрудника",
    "Full details →": "Подробнее →",
    "Skilled Employer Sponsored Regional": "Региональное спонсорство квалифицированных работников",
    "Subclass 494": "Подкласс 494",
    "For regional employers": "Для региональных работодателей",
    "DAMA concessions: age, English, salary, occupation lists": "Уступки DAMA: возраст, английский, зарплата, списки профессий",
    "5-year visa with 191 PR pathway": "Виза на 5 лет с путём к постоянному резидентству (191)",
    "We handle DAMA endorsement end to end": "Мы ведём одобрение DAMA под ключ",
    "Employer Nomination Scheme": "Схема номинации работодателя",
    "Subclass 186": "Подкласс 186",
    "Permanent residency for key staff": "Постоянное резидентство для ключевых сотрудников",
    "Direct Entry or 482 transition": "Прямой въезд или переход с 482",
    "Retention tool your competitors may not offer": "Инструмент удержания, которого у конкурентов может не быть",
    "Genuine-position documentation handled": "Документация по реальности должности — на нас",
    "The Ground Rules": "Основные правила",
    "Occupation lists and salary floors,<span class=\"text-gold-500\"> in plain English</span>": "Списки профессий и зарплатные пороги,<span class=\"text-gold-500\"> простым языком</span>",
    "Two gates decide every sponsorship: <strong class=\"text-navy-800 dark:text-white\">is the occupation eligible?</strong> and <strong class=\"text-navy-800 dark:text-white\">does the salary meet the floor?</strong> Here are the current settings — we confirm your specific role before you spend anything.": "Каждое спонсорство решают два барьера: <strong class=\"text-navy-800 dark:text-white\">подходит ли профессия?</strong> и <strong class=\"text-navy-800 dark:text-white\">достигает ли зарплата порога?</strong> Вот актуальные параметры — вашу конкретную роль мы подтвердим до того, как вы потратите хоть что-то.",
    "Core Skills income threshold": "Порог дохода Core Skills",
    "Minimum salary for the 482 Core Skills stream — the higher of this or the market salary rate applies.": "Минимальная зарплата для потока 482 Core Skills — применяется большая из двух сумм: эта или рыночная ставка зарплаты.",
    "Specialist Skills threshold (SSIT)": "Порог Specialist Skills (SSIT)",
    "From 1 July 2026. Opens the fast-tracked Specialist stream with no occupation list requirement.": "С 1 июля 2026 г. Открывает ускоренный поток Specialist без требования списка профессий.",
    "Core Skills Occupation List": "Список профессий Core Skills",
    "Hundreds of skilled occupations eligible for sponsorship — most professional and trade roles are covered.": "Сотни квалифицированных профессий доступны для спонсорства — покрыты большинство профессиональных и рабочих ролей.",
    "ANZSCO eligibility (Specialist)": "Соответствие ANZSCO (Specialist)",
    "Levels 1–2, 4–6": "Уровни 1–2, 4–6",
    "Specialist stream excludes trades workers, machinery operators and labourers — but needs no list.": "Поток Specialist исключает рабочих специальностей, операторов машин и разнорабочих — но не требует списка.",
    "DAMA — Designated Area Migration Agreements": "DAMA — соглашения о миграции для назначенных регионов",
    "When standard settings don't fit, regional Australia opens a second door.": "Когда стандартные условия не подходят, региональная Австралия открывает вторую дверь.",
    "A DAMA is a formal agreement between the Australian Government and a regional authority. It lets endorsed\n          local employers sponsor workers with <strong class=\"text-white\">concessions standard programs don't offer</strong> —\n          broader occupation lists, lower English and salary thresholds, age concessions — in exchange for committing\n          to the region. For regional businesses, it is often the difference between a filled role and a closed door.": "DAMA — это официальное соглашение между правительством Австралии и региональным органом власти. Оно позволяет одобренным\n          местным работодателям спонсировать работников с <strong class=\"text-white\">уступками, которых нет в стандартных программах</strong> —\n          более широкие списки профессий, сниженные пороги по английскому и зарплате, уступки по возрасту — в обмен на обязательство\n          оставаться в регионе. Для региональных компаний это часто разница между заполненной вакансией и закрытой дверью.",
    "Where DAMA wins": "Где DAMA выигрывает",
    "Occupations not on standard lists become sponsorable": "Профессии, которых нет в стандартных списках, становятся доступны для спонсорства",
    "Concessions on English, salary, age and skills where justified": "Уступки по английскому, зарплате, возрасту и навыкам — там, где это обосновано",
    "Permanent residency pathways (via 494 → 191 or 186) that attract committed staff": "Пути к постоянному резидентству (через 494 → 191 или 186), которые привлекают заинтересованных сотрудников",
    "Designed exactly for employers who cannot fill roles locally": "Создано именно для работодателей, которые не могут закрыть вакансии на месте",
    "What to weigh honestly": "Что честно взвесить",
    "Two-stage process: regional endorsement first, then the labour agreement — allow months, not weeks": "Двухэтапный процесс: сначала региональное одобрение, затем трудовое соглашение — закладывайте месяцы, а не недели",
    "Annual nomination caps negotiated per agreement": "Ежегодные квоты номинаций согласовываются по каждому соглашению",
    "Employee must genuinely live and work in the designated region": "Сотрудник должен реально проживать и работать в назначенном регионе",
    "Full sponsorship obligations and compliance monitoring still apply": "Полные обязательства спонсора и мониторинг соответствия остаются в силе",
    "Active DAMA regions": "Активные регионы DAMA",
    "Each agreement has its own occupation list and concession settings — we confirm current terms with the regional authority before advising you.": "У каждого соглашения свои список профессий и параметры уступок — перед рекомендациями мы подтверждаем актуальные условия у регионального органа власти.",
    "Active": "Активна",
    "Concessions:": "Уступки:",
    "Reduced English, lower skills thresholds, broader occupation list, salary concessions for some occupations": "Сниженные требования к английскому, более низкие пороги по навыкам, более широкий список профессий, уступки по зарплате для некоторых профессий",
    "Two DAMAs covering Adelaide and all of regional South Australia — 1,000+ endorsed employers.": "Два DAMA, охватывающих Аделаиду и всю региональную Южную Австралию — более 1 000 одобренных работодателей.",
    "Lower English for some occupations, age concessions up to 50, skills concessions, broader occupation list": "Сниженный английский для некоторых профессий, уступки по возрасту до 50 лет, уступки по навыкам, более широкий список профессий",
    "One DAMA covering the entire NT — all NT employers can access it.": "Один DAMA на всю Северную территорию — доступен всем работодателям NT.",
    "English and skills concessions for selected occupations, PR pathways available": "Уступки по английскому и навыкам для отдельных профессий, доступны пути к постоянному резидентству (PR)",
    "Central and western NSW — Dubbo, Wagga and surrounding areas.": "Центральный и западный Новый Южный Уэльс — Даббо, Уогга и окрестности.",
    "English, skills and experience concessions for selected occupations": "Уступки по английскому, навыкам и опыту для отдельных профессий",
    "Cairns and FNQ — strong support for tourism and hospitality.": "Кэрнс и Дальний Север Квинсленда (FNQ) — мощная поддержка туризма и гостеприимства.",
    "Skills and English concessions for mining-related occupations": "Уступки по навыкам и английскому для профессий, связанных с горнодобычей",
    "Kalgoorlie region — resources sector workforce.": "Регион Калгурли — кадры для сектора ресурсов.",
    "Lower thresholds for dairy, agriculture and manufacturing occupations": "Сниженные пороги для профессий в молочной отрасли, сельском хозяйстве и производстве",
    "Regional Victoria — farming and agricultural sectors.": "Региональная Виктория — фермерство и сельское хозяйство.",
    "Broader occupation list incl. trades and hospitality, English and skills concessions": "Более широкий список профессий, включая рабочие специальности и гостеприимство, уступки по английскому и навыкам",
    "Bunbury and Margaret River region.": "Регион Банбери и Маргарет-Ривер.",
    "Skills and experience concessions for mining and resources occupations": "Уступки по навыкам и опыту для профессий в горнодобыче и ресурсном секторе",
    "FIFO and residential workforce needs.": "Потребности в вахтовых (FIFO) и проживающих на месте работниках.",
    "Lower English, broader occupation list incl. tourism and hospitality": "Сниженный английский, более широкий список профессий, включая туризм и гостеприимство",
    "Tourism and remote community services.": "Туризм и услуги для удалённых сообществ.",
    "Similar concessions with tourism and hospitality focus": "Аналогичные уступки с фокусом на туризм и гостеприимство",
    "Broome and surrounding areas.": "Брум и окрестности.",
    "Not sure if your region qualifies?": "Не уверены, подходит ли ваш регион?",
    "DAMA consultation (1 hour, $330 AUD) — we map your role, region and concessions, and tell you plainly whether DAMA is worth pursuing.": "Консультация по DAMA (1 час, $330 AUD) — мы разберём вашу роль, регион и уступки и прямо скажем, стоит ли заниматься DAMA.",
    "Book a DAMA consultation": "Записаться на консультацию по DAMA",
    "Compliance, handled": "Соответствие — под ключ",
    "Sponsorship obligations are real — and manageable.": "Обязательства спонсора реальны — и выполнимы.",
    "Sponsors take on legal obligations for the life of the sponsorship. None of them are difficult with the right\n          settings from day one — we build compliance into the application, not after it.": "Спонсоры берут на себя юридические обязательства на весь срок спонсорства. Ни одно из них не сложно, если с первого дня\n          правильно настроить процесс — мы закладываем соответствие требованиям в заявку, а не после неё.",
    "Pay at least the market salary rate and the relevant income threshold": "Платить не ниже рыночной ставки зарплаты и соответствующего порога дохода",
    "Pay the Skilling Australians Fund (SAF) levy for each nomination": "Платить сбор в Skilling Australians Fund (SAF) за каждую номинацию",
    "Ensure the worker works only in the nominated occupation": "Обеспечить, чтобы работник трудился только по номинированной профессии",
    "Notify the Department of prescribed changes (role, location, business structure)": "Уведомлять Департамент о предписанных изменениях (роль, место работы, структура бизнеса)",
    "Cooperate with monitoring — records must be audit-ready": "Сотрудничать при мониторинге — записи должны быть готовы к проверке",
    "Never recover sponsorship or nomination costs from the visa holder": "Никогда не взыскивать расходы на спонсорство или номинацию с держателя визы",
    "How It Works": "Как это работает",
    "From vacancy to visa grant in<span class=\"text-gold-500\"> four steps</span>": "От вакансии до выдачи визы за<span class=\"text-gold-500\"> четыре шага</span>",
    "Feasibility": "Оценка возможностей",
    "We confirm your eligibility to sponsor, the right program, and honest costs — before you commit.": "Мы подтверждаем ваше право спонсировать, подходящую программу и честную стоимость — до того, как вы возьмёте на себя обязательства.",
    "Sponsorship": "Спонсорство",
    "SBS or labour agreement application prepared and lodged, with compliance settings from day one.": "Заявка на SBS или трудовое соглашение готовится и подаётся с настройками соответствия с первого дня.",
    "Nomination &amp; Visa": "Номинация и виза",
    "Position, salary (AMSR/threshold), LMT and the employee&#39;s visa — managed as one project.": "Должность, зарплата (AMSR/порог), LMT и виза сотрудника — ведутся как один проект.",
    "Compliance &amp; PR": "Соответствие и ПМЖ",
    "Sponsorship obligations, monitoring, and the PR pathway (186/191) planned from the start.": "Обязательства спонсора, мониторинг и путь к постоянному резидентству (186/191) планируются с самого начала.",
    "Ready to sponsor skilled workers?": "Готовы спонсировать квалифицированных сотрудников?",
    "Book an employer consultation — we&#39;ll assess your eligibility, the right program, and give you a fixed-fee quote. Consultations $330 AUD per hour.": "Запишитесь на консультацию для работодателей — мы оценим ваше право на спонсорство, подходящую программу и дадим расценку с фиксированной ценой. Консультации — $330 AUD в час.",
    "Book a consultation →": "Записаться на консультацию →",
    "Detailed Visa Assessment": "Детальная оценка визы",
    # ---- privacy.html ----
    "Privacy Policy &amp; Terms | Visa2AU": "Политика конфиденциальности &amp; условия | Visa2AU",
    "How Visa2AU collects, uses and protects your personal information, and the terms of using this website.": "Как Visa2AU собирает, использует и защищает ваши персональные данные, а также условия использования этого сайта.",
    "Privacy Policy & <span class=\"text-gold-400\">Terms</span>": "Политика конфиденциальности и <span class=\"text-gold-400\">условия</span>",
    "Privacy Policy": "Политика конфиденциальности",
    "Visa2AU Pty Ltd (ABN 36676512397) handles personal information in accordance with the Privacy Act 1988 (Cth) and the Australian Privacy Principles (APPs).": "Компания Visa2AU Pty Ltd (ABN 36676512397) обрабатывает персональные данные в соответствии с Privacy Act 1988 (Cth) и Австралийскими принципами конфиденциальности (APPs).",
    "What we collect": "Что мы собираем",
    "Contact details you submit via forms (name, email, phone, message).": "Контактные данные, которые вы отправляете через формы (имя, email, телефон, сообщение).",
    "Payment identifiers when you pay an invoice (processed by Stripe — card details never touch our servers).": "Платёжные идентификаторы при оплате счёта (обрабатываются Stripe — данные карты никогда не попадают на наши серверы).",
    "Video consultation metadata (hosted by Daily.co; consultations are recorded for quality and compliance with your consent shown before joining).": "Метаданные видеоконсультаций (размещаются на Daily.co; консультации записываются для контроля качества и соблюдения требований с вашего согласия, которое запрашивается перед началом).",
    "Voice assistant interactions (processed by ElevenLabs, where enabled) used to respond to your enquiry.": "Взаимодействия с голосовым ассистентом (обрабатываются ElevenLabs, где он включён), используемые для ответа на ваш запрос.",
    "How we use it": "Как мы используем данные",
    "To respond to enquiries, provide migration services, meet our professional obligations, and improve this website. We do not sell personal information.": "Чтобы отвечать на запросы, оказывать миграционные услуги, выполнять наши профессиональные обязательства и улучшать этот сайт. Мы не продаём персональные данные.",
    "Cross-border disclosure": "Передача данных за границу",
    "Some service providers (Stripe, Daily.co, ElevenLabs, Cloudflare) process data overseas. We take reasonable steps to ensure they handle it consistently with the APPs (APP 8).": "Некоторые поставщики услуг (Stripe, Daily.co, ElevenLabs, Cloudflare) обрабатывают данные за рубежом. Мы предпринимаем разумные меры, чтобы они обрабатывали их в соответствии с APPs (APP 8).",
    "Access and correction": "Доступ и исправление",
    "You may request access to, or correction of, your personal information at any time via": "Вы можете в любое время запросить доступ к своим персональным данным или их исправление по адресу",
    "Terms of Use": "Условия использования",
    "Information, not advice": "Информация, а не консультация",
    "Content on this website — including visa guides, the Pathway Finder, search results and the voice assistant — is general information only. It is not migration advice, cannot replace a consultation with a registered migration agent, and may not reflect the latest legislative changes. Individual advice is provided only under a written engagement.": "Содержимое этого сайта — включая визовые гайды, Pathway Finder, результаты поиска и голосового ассистента — носит исключительно информационный характер. Это не миграционная консультация, оно не заменяет консультацию зарегистрированного миграционного агента и может не отражать последние изменения законодательства. Индивидуальные консультации предоставляются только в рамках письменного договора.",
    "Registrations": "Регистрации",
    "Migration advice is provided by registered migration agents: MARN 0534230 (N. Arens), 2418663 (S. Vinnichenko), operating under the Migration Agents Code of Conduct (mara.gov.au).": "Миграционные консультации предоставляют зарегистрированные миграционные агенты: MARN 0534230 (N. Arens), 2418663 (S. Vinnichenko), работающие в соответствии с Migration Agents Code of Conduct (mara.gov.au).",
    "Historical results": "Исторические результаты",
    "Success-rate figures describe our historical record and do not guarantee the outcome of any future application.": "Показатели успешности описывают нашу историческую статистику и не гарантируют результат любого будущего заявления.",
    "Contact": "Контакты",
}
